packages:
  - .
autoInstallPeers: true
configDependencies:
  "@savvy-web/pnpm-plugin-silk": 0.13.1+sha512-JcdSuckKQRFx38Fb8uqROEDC6N0e0PbDkRBP92fURIwZjGKUaxk3xQVaFeW3owos9f8uRRQbKlt3nZQNDAQ5Zw==
loglevel: info
