#!/usr/bin/env npx tsx
/**
 * Fetches current runtime version data and generates fully-typed TypeScript
 * default files in src/data/. Only writes when content has actually changed.
 *
 * Usage: npx tsx lib/scripts/generate-defaults.mts
 */
import * as fs from "node:fs";
import * as path from "node:path";
import { Effect, Layer, Schema } from "effect";
import { GitHubClientLive } from "../../src/layers/GitHubClientLive.js";
import { GitHubTokenAuth } from "../../src/layers/GitHubTokenAuth.js";
import { ParseError } from "../../src/errors/ParseError.js";
import { GitHubTagList } from "../../src/schemas/github.js";
import type { GitHubTag } from "../../src/schemas/github.js";
import { NodeDistIndex, NodeReleaseSchedule } from "../../src/schemas/node.js";
import type { NodeDistVersion, ReleaseScheduleEntry } from "../../src/schemas/node.js";
import { GitHubClient } from "../../src/services/GitHubClient.js";

const DATA_DIR = path.resolve(import.meta.dirname, "../../src/data");

const decodeNodeDist = Schema.decodeUnknown(NodeDistIndex);
const decodeSchedule = Schema.decodeUnknown(NodeReleaseSchedule);
const decodeTagList = Schema.decodeUnknown(GitHubTagList);

const mapParseError = (e: import("effect/ParseResult").ParseError) =>
	new ParseError({ source: "generate-defaults", message: `Schema validation failed: ${e.message}` });

// --- Code generators ---

const GENERATED_HEADER = `// AUTO-GENERATED by lib/scripts/generate-defaults.mts — do not edit manually`;

function generateNodeDefaults(
	versions: ReadonlyArray<NodeDistVersion>,
	schedule: { readonly [key: string]: ReleaseScheduleEntry },
): string {
	const lines: string[] = [
		GENERATED_HEADER,
		`import type { NodeDistVersion, ReleaseScheduleEntry } from "../schemas/node.js";`,
		"",
		`export const nodeDefaultVersions: ReadonlyArray<NodeDistVersion> = ${JSON.stringify(versions, null, "\t")} as const;`,
		"",
		`export const nodeDefaultSchedule: Readonly<Record<string, ReleaseScheduleEntry>> = ${JSON.stringify(schedule, null, "\t")} as const;`,
		"",
	];
	return lines.join("\n");
}

function generateTagDefaults(runtime: "bun" | "deno", tags: ReadonlyArray<GitHubTag>): string {
	const varName = `${runtime}DefaultTags`;
	const lines: string[] = [
		GENERATED_HEADER,
		`import type { GitHubTag } from "../schemas/github.js";`,
		"",
		`export const ${varName}: ReadonlyArray<GitHubTag> = ${JSON.stringify(tags, null, "\t")} as const;`,
		"",
	];
	return lines.join("\n");
}

// --- Write with content check ---

function writeIfChanged(filePath: string, content: string): boolean {
	if (fs.existsSync(filePath)) {
		const existing = fs.readFileSync(filePath, "utf-8");
		if (existing === content) {
			return false;
		}
	}
	fs.writeFileSync(filePath, content);
	return true;
}

// --- Main program ---

const nodeDistSchema = {
	decode: (input: unknown) => decodeNodeDist(input).pipe(Effect.mapError(mapParseError)),
};

const scheduleSchema = {
	decode: (input: unknown) => decodeSchedule(input).pipe(Effect.mapError(mapParseError)),
};

const program = Effect.gen(function* () {
	const client = yield* GitHubClient;

	console.log("Fetching runtime data...");

	const [bunTagsRaw, denoTagsRaw, nodeVersions, schedule] = yield* Effect.all([
		client.listTags("oven-sh", "bun", { perPage: 100 }),
		client.listTags("denoland", "deno", { perPage: 100 }),
		client.getJson("https://nodejs.org/dist/index.json", nodeDistSchema),
		client.getJson(
			"https://raw.githubusercontent.com/nodejs/Release/main/schedule.json",
			scheduleSchema,
		),
	]);

	// Validate tag data through schema
	const bunTags = yield* decodeTagList(bunTagsRaw).pipe(
		Effect.mapError(
			(e) => new ParseError({ source: "bun-tags", message: `Schema validation failed: ${e.message}` }),
		),
	);
	const denoTags = yield* decodeTagList(denoTagsRaw).pipe(
		Effect.mapError(
			(e) => new ParseError({ source: "deno-tags", message: `Schema validation failed: ${e.message}` }),
		),
	);

	// Generate TypeScript source files
	const nodeContent = generateNodeDefaults(nodeVersions, schedule);
	const bunContent = generateTagDefaults("bun", bunTags);
	const denoContent = generateTagDefaults("deno", denoTags);

	// Write only if changed
	const nodeChanged = writeIfChanged(path.join(DATA_DIR, "node-defaults.ts"), nodeContent);
	const bunChanged = writeIfChanged(path.join(DATA_DIR, "bun-defaults.ts"), bunContent);
	const denoChanged = writeIfChanged(path.join(DATA_DIR, "deno-defaults.ts"), denoContent);

	return { nodeChanged, bunChanged, denoChanged, nodeVersions: nodeVersions.length, bunTags: bunTags.length, denoTags: denoTags.length };
});

const AppLayer = GitHubClientLive.pipe(Layer.provide(GitHubTokenAuth));

Effect.runPromise(program.pipe(Effect.provide(AppLayer)))
	.then(({ nodeChanged, bunChanged, denoChanged, nodeVersions, bunTags, denoTags }) => {
		console.log("Generated defaults:");
		console.log(`  node-defaults.ts: ${nodeVersions} versions ${nodeChanged ? "(updated)" : "(unchanged)"}`);
		console.log(`  bun-defaults.ts:  ${bunTags} tags ${bunChanged ? "(updated)" : "(unchanged)"}`);
		console.log(`  deno-defaults.ts: ${denoTags} tags ${denoChanged ? "(updated)" : "(unchanged)"}`);
	})
	.catch((err) => {
		console.error("Failed to generate defaults:", err);
		process.exit(1);
	});
