#!/usr/bin/env npx tsx
/**
 * Fetches current runtime version data and generates fully-typed TypeScript
 * default files in src/data/. Only writes when content has actually changed.
 *
 * Usage: npx tsx lib/scripts/generate-defaults.mts
 */
import * as fs from "node:fs";
import * as path from "node:path";
import { Effect, Layer, Schema } from "effect";
import { ParseError } from "../../src/errors/ParseError.js";
import { GitHubClientLive } from "../../src/layers/GitHubClientLive.js";
import { GitHubTokenAuth } from "../../src/layers/GitHubTokenAuth.js";
import type { NodeDistVersion, NodeReleaseSchedule as NodeReleaseScheduleType } from "../../src/schemas/node.js";
import { NodeDistIndex, NodeReleaseSchedule } from "../../src/schemas/node.js";
import { GitHubClient } from "../../src/services/GitHubClient.js";

const DATA_DIR = path.resolve(import.meta.dirname, "../../src/data");

const decodeNodeDist = Schema.decodeUnknown(NodeDistIndex);
const decodeSchedule = Schema.decodeUnknown(NodeReleaseSchedule);

const mapParseError = (e: import("effect/ParseResult").ParseError) =>
	new ParseError({ source: "generate-defaults", message: `Schema validation failed: ${e.message}` });

// --- Code generators ---

const GENERATED_HEADER = `// AUTO-GENERATED by lib/scripts/generate-defaults.mts — do not edit manually`;

function generateNodeDefaults(versions: ReadonlyArray<NodeDistVersion>, schedule: NodeReleaseScheduleType): string {
	const inputs = versions.map((v) => ({
		version: v.version.replace(/^v/, ""),
		npm: v.npm !== undefined ? v.npm : "0.0.0",
		date: v.date,
	}));
	const lines: string[] = [
		GENERATED_HEADER,
		`import type { NodeReleaseInput } from "../schemas/node-release.js";`,
		`import type { NodeScheduleData } from "../schemas/node-schedule.js";`,
		"",
		`export const nodeDefaultInputs: ReadonlyArray<NodeReleaseInput> = ${JSON.stringify(inputs, null, "\t")} as const;`,
		"",
		`export const nodeDefaultScheduleData: NodeScheduleData = ${JSON.stringify(schedule, null, "\t")} as const;`,
		"",
	];
	return lines.join("\n");
}

function generateReleaseDefaults(
	runtime: "bun" | "deno",
	releases: ReadonlyArray<{
		tag_name: string;
		published_at: string | null;
		draft: boolean;
		prerelease: boolean;
		[k: string]: unknown;
	}>,
): string {
	const prefix = runtime === "bun" ? "bun-" : "";
	const inputs = releases
		.filter((r) => !r.draft && !r.prerelease)
		.map((r) => {
			let version = r.tag_name;
			if (version.startsWith(prefix)) version = version.slice(prefix.length);
			if (version.startsWith("v") || version.startsWith("V")) version = version.slice(1);
			return {
				version,
				date: r.published_at ?? "",
			};
		})
		.filter((input) => /^\d+\.\d+\.\d+/.test(input.version));

	const varName = `${runtime}DefaultInputs`;
	const lines: string[] = [
		GENERATED_HEADER,
		`import type { RuntimeReleaseInput } from "../schemas/runtime-release.js";`,
		"",
		`export const ${varName}: ReadonlyArray<RuntimeReleaseInput> = ${JSON.stringify(inputs, null, "\t")} as const;`,
		"",
	];
	return lines.join("\n");
}

// --- Write with content check ---

function writeIfChanged(filePath: string, content: string): boolean {
	if (fs.existsSync(filePath)) {
		const existing = fs.readFileSync(filePath, "utf-8");
		if (existing === content) {
			return false;
		}
	}
	fs.writeFileSync(filePath, content);
	return true;
}

// --- Main program ---

const nodeDistSchema = {
	decode: (input: unknown) => decodeNodeDist(input).pipe(Effect.mapError(mapParseError)),
};

const scheduleSchema = {
	decode: (input: unknown) => decodeSchedule(input).pipe(Effect.mapError(mapParseError)),
};

const program = Effect.gen(function* () {
	const client = yield* GitHubClient;
	console.log("Fetching runtime data...");

	const [bunReleases, denoReleases, nodeVersions, schedule] = yield* Effect.all([
		client.listReleases("oven-sh", "bun", { perPage: 100 }),
		client.listReleases("denoland", "deno", { perPage: 100 }),
		client.getJson("https://nodejs.org/dist/index.json", nodeDistSchema),
		client.getJson("https://raw.githubusercontent.com/nodejs/Release/main/schedule.json", scheduleSchema),
	]);

	const nodeContent = generateNodeDefaults(nodeVersions, schedule);
	const bunContent = generateReleaseDefaults("bun", bunReleases);
	const denoContent = generateReleaseDefaults("deno", denoReleases);

	const nodeChanged = writeIfChanged(path.join(DATA_DIR, "node-defaults.ts"), nodeContent);
	const bunChanged = writeIfChanged(path.join(DATA_DIR, "bun-defaults.ts"), bunContent);
	const denoChanged = writeIfChanged(path.join(DATA_DIR, "deno-defaults.ts"), denoContent);

	return {
		nodeChanged,
		bunChanged,
		denoChanged,
		nodeVersions: nodeVersions.length,
		bunReleases: bunReleases.length,
		denoReleases: denoReleases.length,
	};
});

const AppLayer = GitHubClientLive.pipe(Layer.provide(GitHubTokenAuth));

Effect.runPromise(program.pipe(Effect.provide(AppLayer)))
	.then(({ nodeChanged, bunChanged, denoChanged, nodeVersions, bunReleases, denoReleases }) => {
		console.log("Generated defaults:");
		console.log(`  node-defaults.ts: ${nodeVersions} versions ${nodeChanged ? "(updated)" : "(unchanged)"}`);
		console.log(`  bun-defaults.ts:  ${bunReleases} releases ${bunChanged ? "(updated)" : "(unchanged)"}`);
		console.log(`  deno-defaults.ts: ${denoReleases} releases ${denoChanged ? "(updated)" : "(unchanged)"}`);
	})
	.catch((err) => {
		console.error("Failed to generate defaults:", err);
		process.exit(1);
	});
