// AUTO-GENERATED by lib/scripts/generate-defaults.mts — do not edit manually
import type { GitHubTag } from "../schemas/github.js";

export const bunDefaultTags: ReadonlyArray<GitHubTag> = [
	{
		name: "v0.1.1",
		zipball_url: "https://api.github.com/repos/oven-sh/bun/zipball/refs/tags/v0.1.1",
		tarball_url: "https://api.github.com/repos/oven-sh/bun/tarball/refs/tags/v0.1.1",
		commit: {
			sha: "a027e9b6bc1c27066f8756f4f8c5cf2a94e1a868",
			url: "https://api.github.com/repos/oven-sh/bun/commits/a027e9b6bc1c27066f8756f4f8c5cf2a94e1a868",
		},
		node_id: "MDM6UmVmMzU3NzI4OTY5OnJlZnMvdGFncy92MC4xLjE=",
	},
	{
		name: "v0.0.0",
		zipball_url: "https://api.github.com/repos/oven-sh/bun/zipball/refs/tags/v0.0.0",
		tarball_url: "https://api.github.com/repos/oven-sh/bun/tarball/refs/tags/v0.0.0",
		commit: {
			sha: "0f7bc76f39b6792052be799779e8d10ee03c564c",
			url: "https://api.github.com/repos/oven-sh/bun/commits/0f7bc76f39b6792052be799779e8d10ee03c564c",
		},
		node_id: "MDM6UmVmMzU3NzI4OTY5OnJlZnMvdGFncy92MC4wLjA=",
	},
	{
		name: "v0.0.0-21",
		zipball_url: "https://api.github.com/repos/oven-sh/bun/zipball/refs/tags/v0.0.0-21",
		tarball_url: "https://api.github.com/repos/oven-sh/bun/tarball/refs/tags/v0.0.0-21",
		commit: {
			sha: "8721ba7474297850ad8f7ab98e90e8301cef1757",
			url: "https://api.github.com/repos/oven-sh/bun/commits/8721ba7474297850ad8f7ab98e90e8301cef1757",
		},
		node_id: "MDM6UmVmMzU3NzI4OTY5OnJlZnMvdGFncy92MC4wLjAtMjE=",
	},
	{
		name: "v0.0.0-20",
		zipball_url: "https://api.github.com/repos/oven-sh/bun/zipball/refs/tags/v0.0.0-20",
		tarball_url: "https://api.github.com/repos/oven-sh/bun/tarball/refs/tags/v0.0.0-20",
		commit: {
			sha: "d7a5b604053889cb564d0098b081b4d95e6509ba",
			url: "https://api.github.com/repos/oven-sh/bun/commits/d7a5b604053889cb564d0098b081b4d95e6509ba",
		},
		node_id: "MDM6UmVmMzU3NzI4OTY5OnJlZnMvdGFncy92MC4wLjAtMjA=",
	},
	{
		name: "v0.0.0-19",
		zipball_url: "https://api.github.com/repos/oven-sh/bun/zipball/refs/tags/v0.0.0-19",
		tarball_url: "https://api.github.com/repos/oven-sh/bun/tarball/refs/tags/v0.0.0-19",
		commit: {
			sha: "2ebe9ad101882cb112a99156414a6fd98244c624",
			url: "https://api.github.com/repos/oven-sh/bun/commits/2ebe9ad101882cb112a99156414a6fd98244c624",
		},
		node_id: "MDM6UmVmMzU3NzI4OTY5OnJlZnMvdGFncy92MC4wLjAtMTk=",
	},
	{
		name: "not-quite-v0",
		zipball_url: "https://api.github.com/repos/oven-sh/bun/zipball/refs/tags/not-quite-v0",
		tarball_url: "https://api.github.com/repos/oven-sh/bun/tarball/refs/tags/not-quite-v0",
		commit: {
			sha: "4f0d4cee0be523bcaeaa85e80309526bdf5cd91e",
			url: "https://api.github.com/repos/oven-sh/bun/commits/4f0d4cee0be523bcaeaa85e80309526bdf5cd91e",
		},
		node_id: "MDM6UmVmMzU3NzI4OTY5OnJlZnMvdGFncy9ub3QtcXVpdGUtdjA=",
	},
	{
		name: "canary",
		zipball_url: "https://api.github.com/repos/oven-sh/bun/zipball/refs/tags/canary",
		tarball_url: "https://api.github.com/repos/oven-sh/bun/tarball/refs/tags/canary",
		commit: {
			sha: "0d4b4c494243cf73bf704971dcc0711c5882a8aa",
			url: "https://api.github.com/repos/oven-sh/bun/commits/0d4b4c494243cf73bf704971dcc0711c5882a8aa",
		},
		node_id: "MDM6UmVmMzU3NzI4OTY5OnJlZnMvdGFncy9jYW5hcnk=",
	},
	{
		name: "bun-v1.3.10",
		zipball_url: "https://api.github.com/repos/oven-sh/bun/zipball/refs/tags/bun-v1.3.10",
		tarball_url: "https://api.github.com/repos/oven-sh/bun/tarball/refs/tags/bun-v1.3.10",
		commit: {
			sha: "30e609e08073cf7114bfb278506962a5b19d0677",
			url: "https://api.github.com/repos/oven-sh/bun/commits/30e609e08073cf7114bfb278506962a5b19d0677",
		},
		node_id: "MDM6UmVmMzU3NzI4OTY5OnJlZnMvdGFncy9idW4tdjEuMy4xMA==",
	},
	{
		name: "bun-v1.3.9",
		zipball_url: "https://api.github.com/repos/oven-sh/bun/zipball/refs/tags/bun-v1.3.9",
		tarball_url: "https://api.github.com/repos/oven-sh/bun/tarball/refs/tags/bun-v1.3.9",
		commit: {
			sha: "cf6cdbbbadd50604bc17f21ed5d0612c920a5d9a",
			url: "https://api.github.com/repos/oven-sh/bun/commits/cf6cdbbbadd50604bc17f21ed5d0612c920a5d9a",
		},
		node_id: "MDM6UmVmMzU3NzI4OTY5OnJlZnMvdGFncy9idW4tdjEuMy45",
	},
	{
		name: "bun-v1.3.8",
		zipball_url: "https://api.github.com/repos/oven-sh/bun/zipball/refs/tags/bun-v1.3.8",
		tarball_url: "https://api.github.com/repos/oven-sh/bun/tarball/refs/tags/bun-v1.3.8",
		commit: {
			sha: "b64edcb490b486fb8af90cb2cb2dc51590453064",
			url: "https://api.github.com/repos/oven-sh/bun/commits/b64edcb490b486fb8af90cb2cb2dc51590453064",
		},
		node_id: "MDM6UmVmMzU3NzI4OTY5OnJlZnMvdGFncy9idW4tdjEuMy44",
	},
	{
		name: "bun-v1.3.7",
		zipball_url: "https://api.github.com/repos/oven-sh/bun/zipball/refs/tags/bun-v1.3.7",
		tarball_url: "https://api.github.com/repos/oven-sh/bun/tarball/refs/tags/bun-v1.3.7",
		commit: {
			sha: "ba426210c28a43a3d36db504523617fd0202070e",
			url: "https://api.github.com/repos/oven-sh/bun/commits/ba426210c28a43a3d36db504523617fd0202070e",
		},
		node_id: "MDM6UmVmMzU3NzI4OTY5OnJlZnMvdGFncy9idW4tdjEuMy43",
	},
	{
		name: "bun-v1.3.6",
		zipball_url: "https://api.github.com/repos/oven-sh/bun/zipball/refs/tags/bun-v1.3.6",
		tarball_url: "https://api.github.com/repos/oven-sh/bun/tarball/refs/tags/bun-v1.3.6",
		commit: {
			sha: "d530ed993d62be7c7f8f01a3d52627b6845dfd93",
			url: "https://api.github.com/repos/oven-sh/bun/commits/d530ed993d62be7c7f8f01a3d52627b6845dfd93",
		},
		node_id: "MDM6UmVmMzU3NzI4OTY5OnJlZnMvdGFncy9idW4tdjEuMy42",
	},
	{
		name: "bun-v1.3.5",
		zipball_url: "https://api.github.com/repos/oven-sh/bun/zipball/refs/tags/bun-v1.3.5",
		tarball_url: "https://api.github.com/repos/oven-sh/bun/tarball/refs/tags/bun-v1.3.5",
		commit: {
			sha: "fa5a5bbe556a4bda5bde77b4013aa6c3bb4ec9ab",
			url: "https://api.github.com/repos/oven-sh/bun/commits/fa5a5bbe556a4bda5bde77b4013aa6c3bb4ec9ab",
		},
		node_id: "MDM6UmVmMzU3NzI4OTY5OnJlZnMvdGFncy9idW4tdjEuMy41",
	},
	{
		name: "bun-v1.3.4",
		zipball_url: "https://api.github.com/repos/oven-sh/bun/zipball/refs/tags/bun-v1.3.4",
		tarball_url: "https://api.github.com/repos/oven-sh/bun/tarball/refs/tags/bun-v1.3.4",
		commit: {
			sha: "5eb2145b3104f48eadd601518904e56aaa9937bf",
			url: "https://api.github.com/repos/oven-sh/bun/commits/5eb2145b3104f48eadd601518904e56aaa9937bf",
		},
		node_id: "MDM6UmVmMzU3NzI4OTY5OnJlZnMvdGFncy9idW4tdjEuMy40",
	},
	{
		name: "bun-v1.3.3",
		zipball_url: "https://api.github.com/repos/oven-sh/bun/zipball/refs/tags/bun-v1.3.3",
		tarball_url: "https://api.github.com/repos/oven-sh/bun/tarball/refs/tags/bun-v1.3.3",
		commit: {
			sha: "abb1b0c4d75acabf1742b951a1f739068c94a7bd",
			url: "https://api.github.com/repos/oven-sh/bun/commits/abb1b0c4d75acabf1742b951a1f739068c94a7bd",
		},
		node_id: "MDM6UmVmMzU3NzI4OTY5OnJlZnMvdGFncy9idW4tdjEuMy4z",
	},
	{
		name: "bun-v1.3.2",
		zipball_url: "https://api.github.com/repos/oven-sh/bun/zipball/refs/tags/bun-v1.3.2",
		tarball_url: "https://api.github.com/repos/oven-sh/bun/tarball/refs/tags/bun-v1.3.2",
		commit: {
			sha: "b131639cc545af23e568feb68e7d5c14c2778b20",
			url: "https://api.github.com/repos/oven-sh/bun/commits/b131639cc545af23e568feb68e7d5c14c2778b20",
		},
		node_id: "MDM6UmVmMzU3NzI4OTY5OnJlZnMvdGFncy9idW4tdjEuMy4y",
	},
	{
		name: "bun-v1.3.1",
		zipball_url: "https://api.github.com/repos/oven-sh/bun/zipball/refs/tags/bun-v1.3.1",
		tarball_url: "https://api.github.com/repos/oven-sh/bun/tarball/refs/tags/bun-v1.3.1",
		commit: {
			sha: "89fa0f343945e61d5e4a0077cc7e93a802ed56e7",
			url: "https://api.github.com/repos/oven-sh/bun/commits/89fa0f343945e61d5e4a0077cc7e93a802ed56e7",
		},
		node_id: "MDM6UmVmMzU3NzI4OTY5OnJlZnMvdGFncy9idW4tdjEuMy4x",
	},
	{
		name: "bun-v1.3.0",
		zipball_url: "https://api.github.com/repos/oven-sh/bun/zipball/refs/tags/bun-v1.3.0",
		tarball_url: "https://api.github.com/repos/oven-sh/bun/tarball/refs/tags/bun-v1.3.0",
		commit: {
			sha: "b0a6feca57bf5c2a9ec2ef9773499cab7d904b30",
			url: "https://api.github.com/repos/oven-sh/bun/commits/b0a6feca57bf5c2a9ec2ef9773499cab7d904b30",
		},
		node_id: "MDM6UmVmMzU3NzI4OTY5OnJlZnMvdGFncy9idW4tdjEuMy4w",
	},
	{
		name: "bun-v1.2.23",
		zipball_url: "https://api.github.com/repos/oven-sh/bun/zipball/refs/tags/bun-v1.2.23",
		tarball_url: "https://api.github.com/repos/oven-sh/bun/tarball/refs/tags/bun-v1.2.23",
		commit: {
			sha: "cf1367137da5775dc23cb57f0e4071776e1ff90f",
			url: "https://api.github.com/repos/oven-sh/bun/commits/cf1367137da5775dc23cb57f0e4071776e1ff90f",
		},
		node_id: "MDM6UmVmMzU3NzI4OTY5OnJlZnMvdGFncy9idW4tdjEuMi4yMw==",
	},
	{
		name: "bun-v1.2.22",
		zipball_url: "https://api.github.com/repos/oven-sh/bun/zipball/refs/tags/bun-v1.2.22",
		tarball_url: "https://api.github.com/repos/oven-sh/bun/tarball/refs/tags/bun-v1.2.22",
		commit: {
			sha: "6bafe2602e9a24ad9072664115bc7fd195cf3211",
			url: "https://api.github.com/repos/oven-sh/bun/commits/6bafe2602e9a24ad9072664115bc7fd195cf3211",
		},
		node_id: "MDM6UmVmMzU3NzI4OTY5OnJlZnMvdGFncy9idW4tdjEuMi4yMg==",
	},
	{
		name: "bun-v1.2.21",
		zipball_url: "https://api.github.com/repos/oven-sh/bun/zipball/refs/tags/bun-v1.2.21",
		tarball_url: "https://api.github.com/repos/oven-sh/bun/tarball/refs/tags/bun-v1.2.21",
		commit: {
			sha: "7c45ed97def1264717a1b55ab0f789f2ea58f986",
			url: "https://api.github.com/repos/oven-sh/bun/commits/7c45ed97def1264717a1b55ab0f789f2ea58f986",
		},
		node_id: "MDM6UmVmMzU3NzI4OTY5OnJlZnMvdGFncy9idW4tdjEuMi4yMQ==",
	},
	{
		name: "bun-v1.2.20",
		zipball_url: "https://api.github.com/repos/oven-sh/bun/zipball/refs/tags/bun-v1.2.20",
		tarball_url: "https://api.github.com/repos/oven-sh/bun/tarball/refs/tags/bun-v1.2.20",
		commit: {
			sha: "6ad208bc32e01c20e35e286a3194be60565254fa",
			url: "https://api.github.com/repos/oven-sh/bun/commits/6ad208bc32e01c20e35e286a3194be60565254fa",
		},
		node_id: "MDM6UmVmMzU3NzI4OTY5OnJlZnMvdGFncy9idW4tdjEuMi4yMA==",
	},
	{
		name: "bun-v1.2.19",
		zipball_url: "https://api.github.com/repos/oven-sh/bun/zipball/refs/tags/bun-v1.2.19",
		tarball_url: "https://api.github.com/repos/oven-sh/bun/tarball/refs/tags/bun-v1.2.19",
		commit: {
			sha: "aad3abeaddfb9f875ab6675dbc008a969f9fbe7d",
			url: "https://api.github.com/repos/oven-sh/bun/commits/aad3abeaddfb9f875ab6675dbc008a969f9fbe7d",
		},
		node_id: "MDM6UmVmMzU3NzI4OTY5OnJlZnMvdGFncy9idW4tdjEuMi4xOQ==",
	},
	{
		name: "bun-v1.2.18",
		zipball_url: "https://api.github.com/repos/oven-sh/bun/zipball/refs/tags/bun-v1.2.18",
		tarball_url: "https://api.github.com/repos/oven-sh/bun/tarball/refs/tags/bun-v1.2.18",
		commit: {
			sha: "0d4089ea7c48d339e87cc48f1871aeee745d8112",
			url: "https://api.github.com/repos/oven-sh/bun/commits/0d4089ea7c48d339e87cc48f1871aeee745d8112",
		},
		node_id: "MDM6UmVmMzU3NzI4OTY5OnJlZnMvdGFncy9idW4tdjEuMi4xOA==",
	},
	{
		name: "bun-v1.2.17",
		zipball_url: "https://api.github.com/repos/oven-sh/bun/zipball/refs/tags/bun-v1.2.17",
		tarball_url: "https://api.github.com/repos/oven-sh/bun/tarball/refs/tags/bun-v1.2.17",
		commit: {
			sha: "0b5363099b3a01057106b6582937c465611d539c",
			url: "https://api.github.com/repos/oven-sh/bun/commits/0b5363099b3a01057106b6582937c465611d539c",
		},
		node_id: "MDM6UmVmMzU3NzI4OTY5OnJlZnMvdGFncy9idW4tdjEuMi4xNw==",
	},
	{
		name: "bun-v1.2.16",
		zipball_url: "https://api.github.com/repos/oven-sh/bun/zipball/refs/tags/bun-v1.2.16",
		tarball_url: "https://api.github.com/repos/oven-sh/bun/tarball/refs/tags/bun-v1.2.16",
		commit: {
			sha: "07d3d6c9f694ddffc4e4ab6f14dd5e6334b28037",
			url: "https://api.github.com/repos/oven-sh/bun/commits/07d3d6c9f694ddffc4e4ab6f14dd5e6334b28037",
		},
		node_id: "MDM6UmVmMzU3NzI4OTY5OnJlZnMvdGFncy9idW4tdjEuMi4xNg==",
	},
	{
		name: "bun-v1.2.15",
		zipball_url: "https://api.github.com/repos/oven-sh/bun/zipball/refs/tags/bun-v1.2.15",
		tarball_url: "https://api.github.com/repos/oven-sh/bun/tarball/refs/tags/bun-v1.2.15",
		commit: {
			sha: "df017990aa5dd95b4028a74be5fa6e40947f9857",
			url: "https://api.github.com/repos/oven-sh/bun/commits/df017990aa5dd95b4028a74be5fa6e40947f9857",
		},
		node_id: "MDM6UmVmMzU3NzI4OTY5OnJlZnMvdGFncy9idW4tdjEuMi4xNQ==",
	},
	{
		name: "bun-v1.2.14",
		zipball_url: "https://api.github.com/repos/oven-sh/bun/zipball/refs/tags/bun-v1.2.14",
		tarball_url: "https://api.github.com/repos/oven-sh/bun/tarball/refs/tags/bun-v1.2.14",
		commit: {
			sha: "6a363a38da9b4a8bc3f4f8ab0bdb75876af488a6",
			url: "https://api.github.com/repos/oven-sh/bun/commits/6a363a38da9b4a8bc3f4f8ab0bdb75876af488a6",
		},
		node_id: "MDM6UmVmMzU3NzI4OTY5OnJlZnMvdGFncy9idW4tdjEuMi4xNA==",
	},
	{
		name: "bun-v1.2.13",
		zipball_url: "https://api.github.com/repos/oven-sh/bun/zipball/refs/tags/bun-v1.2.13",
		tarball_url: "https://api.github.com/repos/oven-sh/bun/tarball/refs/tags/bun-v1.2.13",
		commit: {
			sha: "64ed68c9e0faa7f5224876be8681d2bdc311454b",
			url: "https://api.github.com/repos/oven-sh/bun/commits/64ed68c9e0faa7f5224876be8681d2bdc311454b",
		},
		node_id: "MDM6UmVmMzU3NzI4OTY5OnJlZnMvdGFncy9idW4tdjEuMi4xMw==",
	},
	{
		name: "bun-v1.2.12",
		zipball_url: "https://api.github.com/repos/oven-sh/bun/zipball/refs/tags/bun-v1.2.12",
		tarball_url: "https://api.github.com/repos/oven-sh/bun/tarball/refs/tags/bun-v1.2.12",
		commit: {
			sha: "0785effaab487e8ab475ea2cb067eab60a636257",
			url: "https://api.github.com/repos/oven-sh/bun/commits/0785effaab487e8ab475ea2cb067eab60a636257",
		},
		node_id: "MDM6UmVmMzU3NzI4OTY5OnJlZnMvdGFncy9idW4tdjEuMi4xMg==",
	},
	{
		name: "bun-v1.2.11",
		zipball_url: "https://api.github.com/repos/oven-sh/bun/zipball/refs/tags/bun-v1.2.11",
		tarball_url: "https://api.github.com/repos/oven-sh/bun/tarball/refs/tags/bun-v1.2.11",
		commit: {
			sha: "d4b02dcdc2543cb65c4743aeac7904f380d68a8c",
			url: "https://api.github.com/repos/oven-sh/bun/commits/d4b02dcdc2543cb65c4743aeac7904f380d68a8c",
		},
		node_id: "MDM6UmVmMzU3NzI4OTY5OnJlZnMvdGFncy9idW4tdjEuMi4xMQ==",
	},
	{
		name: "bun-v1.2.10",
		zipball_url: "https://api.github.com/repos/oven-sh/bun/zipball/refs/tags/bun-v1.2.10",
		tarball_url: "https://api.github.com/repos/oven-sh/bun/tarball/refs/tags/bun-v1.2.10",
		commit: {
			sha: "db2e7d7f748dd3951ac0c983de73e75df51bb735",
			url: "https://api.github.com/repos/oven-sh/bun/commits/db2e7d7f748dd3951ac0c983de73e75df51bb735",
		},
		node_id: "MDM6UmVmMzU3NzI4OTY5OnJlZnMvdGFncy9idW4tdjEuMi4xMA==",
	},
	{
		name: "bun-v1.2.9",
		zipball_url: "https://api.github.com/repos/oven-sh/bun/zipball/refs/tags/bun-v1.2.9",
		tarball_url: "https://api.github.com/repos/oven-sh/bun/tarball/refs/tags/bun-v1.2.9",
		commit: {
			sha: "9a329c04cc587f7aa3cce300bbd13f78a16859e7",
			url: "https://api.github.com/repos/oven-sh/bun/commits/9a329c04cc587f7aa3cce300bbd13f78a16859e7",
		},
		node_id: "MDM6UmVmMzU3NzI4OTY5OnJlZnMvdGFncy9idW4tdjEuMi45",
	},
	{
		name: "bun-v1.2.8",
		zipball_url: "https://api.github.com/repos/oven-sh/bun/zipball/refs/tags/bun-v1.2.8",
		tarball_url: "https://api.github.com/repos/oven-sh/bun/tarball/refs/tags/bun-v1.2.8",
		commit: {
			sha: "adab0f64f97c9240026df715006b7a0c42658069",
			url: "https://api.github.com/repos/oven-sh/bun/commits/adab0f64f97c9240026df715006b7a0c42658069",
		},
		node_id: "MDM6UmVmMzU3NzI4OTY5OnJlZnMvdGFncy9idW4tdjEuMi44",
	},
	{
		name: "bun-v1.2.7",
		zipball_url: "https://api.github.com/repos/oven-sh/bun/zipball/refs/tags/bun-v1.2.7",
		tarball_url: "https://api.github.com/repos/oven-sh/bun/tarball/refs/tags/bun-v1.2.7",
		commit: {
			sha: "5c0fa6dc214431a11cbd8279c6629f0fc562881d",
			url: "https://api.github.com/repos/oven-sh/bun/commits/5c0fa6dc214431a11cbd8279c6629f0fc562881d",
		},
		node_id: "MDM6UmVmMzU3NzI4OTY5OnJlZnMvdGFncy9idW4tdjEuMi43",
	},
	{
		name: "bun-v1.2.6",
		zipball_url: "https://api.github.com/repos/oven-sh/bun/zipball/refs/tags/bun-v1.2.6",
		tarball_url: "https://api.github.com/repos/oven-sh/bun/tarball/refs/tags/bun-v1.2.6",
		commit: {
			sha: "8ebd5d53da5c3aa90acfa92a4a6dcc50ea1e18a5",
			url: "https://api.github.com/repos/oven-sh/bun/commits/8ebd5d53da5c3aa90acfa92a4a6dcc50ea1e18a5",
		},
		node_id: "MDM6UmVmMzU3NzI4OTY5OnJlZnMvdGFncy9idW4tdjEuMi42",
	},
	{
		name: "bun-v1.2.5",
		zipball_url: "https://api.github.com/repos/oven-sh/bun/zipball/refs/tags/bun-v1.2.5",
		tarball_url: "https://api.github.com/repos/oven-sh/bun/tarball/refs/tags/bun-v1.2.5",
		commit: {
			sha: "013fdddc6ed18bc849614ccb37a296fa0f69a5db",
			url: "https://api.github.com/repos/oven-sh/bun/commits/013fdddc6ed18bc849614ccb37a296fa0f69a5db",
		},
		node_id: "MDM6UmVmMzU3NzI4OTY5OnJlZnMvdGFncy9idW4tdjEuMi41",
	},
	{
		name: "bun-v1.2.4",
		zipball_url: "https://api.github.com/repos/oven-sh/bun/zipball/refs/tags/bun-v1.2.4",
		tarball_url: "https://api.github.com/repos/oven-sh/bun/tarball/refs/tags/bun-v1.2.4",
		commit: {
			sha: "fd9a5ea668e9ffce5fd5f25a7cfd2d45f0eaa85b",
			url: "https://api.github.com/repos/oven-sh/bun/commits/fd9a5ea668e9ffce5fd5f25a7cfd2d45f0eaa85b",
		},
		node_id: "MDM6UmVmMzU3NzI4OTY5OnJlZnMvdGFncy9idW4tdjEuMi40",
	},
	{
		name: "bun-v1.2.3",
		zipball_url: "https://api.github.com/repos/oven-sh/bun/zipball/refs/tags/bun-v1.2.3",
		tarball_url: "https://api.github.com/repos/oven-sh/bun/tarball/refs/tags/bun-v1.2.3",
		commit: {
			sha: "04703bd3cc682f34da247bf0a13771f38fb61e97",
			url: "https://api.github.com/repos/oven-sh/bun/commits/04703bd3cc682f34da247bf0a13771f38fb61e97",
		},
		node_id: "MDM6UmVmMzU3NzI4OTY5OnJlZnMvdGFncy9idW4tdjEuMi4z",
	},
	{
		name: "bun-v1.2.2",
		zipball_url: "https://api.github.com/repos/oven-sh/bun/zipball/refs/tags/bun-v1.2.2",
		tarball_url: "https://api.github.com/repos/oven-sh/bun/tarball/refs/tags/bun-v1.2.2",
		commit: {
			sha: "c1708ea6ab529a4c747a8282a24d125dc20b0a63",
			url: "https://api.github.com/repos/oven-sh/bun/commits/c1708ea6ab529a4c747a8282a24d125dc20b0a63",
		},
		node_id: "MDM6UmVmMzU3NzI4OTY5OnJlZnMvdGFncy9idW4tdjEuMi4y",
	},
	{
		name: "bun-v1.2.1",
		zipball_url: "https://api.github.com/repos/oven-sh/bun/zipball/refs/tags/bun-v1.2.1",
		tarball_url: "https://api.github.com/repos/oven-sh/bun/tarball/refs/tags/bun-v1.2.1",
		commit: {
			sha: "ce532901ceb43e94f9aa0f5b19a19b8b8b404ae1",
			url: "https://api.github.com/repos/oven-sh/bun/commits/ce532901ceb43e94f9aa0f5b19a19b8b8b404ae1",
		},
		node_id: "MDM6UmVmMzU3NzI4OTY5OnJlZnMvdGFncy9idW4tdjEuMi4x",
	},
	{
		name: "bun-v1.2.0",
		zipball_url: "https://api.github.com/repos/oven-sh/bun/zipball/refs/tags/bun-v1.2.0",
		tarball_url: "https://api.github.com/repos/oven-sh/bun/tarball/refs/tags/bun-v1.2.0",
		commit: {
			sha: "b0c5a7655dac9040655a22754c5eab91046e923b",
			url: "https://api.github.com/repos/oven-sh/bun/commits/b0c5a7655dac9040655a22754c5eab91046e923b",
		},
		node_id: "MDM6UmVmMzU3NzI4OTY5OnJlZnMvdGFncy9idW4tdjEuMi4w",
	},
	{
		name: "bun-v1.1.45",
		zipball_url: "https://api.github.com/repos/oven-sh/bun/zipball/refs/tags/bun-v1.1.45",
		tarball_url: "https://api.github.com/repos/oven-sh/bun/tarball/refs/tags/bun-v1.1.45",
		commit: {
			sha: "196621f253cf318b9096d2b8335b74e0b0e98d6c",
			url: "https://api.github.com/repos/oven-sh/bun/commits/196621f253cf318b9096d2b8335b74e0b0e98d6c",
		},
		node_id: "MDM6UmVmMzU3NzI4OTY5OnJlZnMvdGFncy9idW4tdjEuMS40NQ==",
	},
	{
		name: "bun-v1.1.44",
		zipball_url: "https://api.github.com/repos/oven-sh/bun/zipball/refs/tags/bun-v1.1.44",
		tarball_url: "https://api.github.com/repos/oven-sh/bun/tarball/refs/tags/bun-v1.1.44",
		commit: {
			sha: "6cdcb1c867c9b61ace5edef373508cb7e8161867",
			url: "https://api.github.com/repos/oven-sh/bun/commits/6cdcb1c867c9b61ace5edef373508cb7e8161867",
		},
		node_id: "MDM6UmVmMzU3NzI4OTY5OnJlZnMvdGFncy9idW4tdjEuMS40NA==",
	},
	{
		name: "bun-v1.1.43",
		zipball_url: "https://api.github.com/repos/oven-sh/bun/zipball/refs/tags/bun-v1.1.43",
		tarball_url: "https://api.github.com/repos/oven-sh/bun/tarball/refs/tags/bun-v1.1.43",
		commit: {
			sha: "76800b049a705b02f104089ba70d13b0667a4046",
			url: "https://api.github.com/repos/oven-sh/bun/commits/76800b049a705b02f104089ba70d13b0667a4046",
		},
		node_id: "MDM6UmVmMzU3NzI4OTY5OnJlZnMvdGFncy9idW4tdjEuMS40Mw==",
	},
	{
		name: "bun-v1.1.42",
		zipball_url: "https://api.github.com/repos/oven-sh/bun/zipball/refs/tags/bun-v1.1.42",
		tarball_url: "https://api.github.com/repos/oven-sh/bun/tarball/refs/tags/bun-v1.1.42",
		commit: {
			sha: "50eec0025b482ad7b340c82f64749903b2fad4b8",
			url: "https://api.github.com/repos/oven-sh/bun/commits/50eec0025b482ad7b340c82f64749903b2fad4b8",
		},
		node_id: "MDM6UmVmMzU3NzI4OTY5OnJlZnMvdGFncy9idW4tdjEuMS40Mg==",
	},
	{
		name: "bun-v1.1.41",
		zipball_url: "https://api.github.com/repos/oven-sh/bun/zipball/refs/tags/bun-v1.1.41",
		tarball_url: "https://api.github.com/repos/oven-sh/bun/tarball/refs/tags/bun-v1.1.41",
		commit: {
			sha: "b8f28ed8afd1c2b60568b2b0158d39a674178027",
			url: "https://api.github.com/repos/oven-sh/bun/commits/b8f28ed8afd1c2b60568b2b0158d39a674178027",
		},
		node_id: "MDM6UmVmMzU3NzI4OTY5OnJlZnMvdGFncy9idW4tdjEuMS40MQ==",
	},
	{
		name: "bun-v1.1.40",
		zipball_url: "https://api.github.com/repos/oven-sh/bun/zipball/refs/tags/bun-v1.1.40",
		tarball_url: "https://api.github.com/repos/oven-sh/bun/tarball/refs/tags/bun-v1.1.40",
		commit: {
			sha: "b5b51004e8de80dcd43849e4da1d2623ee3d3008",
			url: "https://api.github.com/repos/oven-sh/bun/commits/b5b51004e8de80dcd43849e4da1d2623ee3d3008",
		},
		node_id: "MDM6UmVmMzU3NzI4OTY5OnJlZnMvdGFncy9idW4tdjEuMS40MA==",
	},
	{
		name: "bun-v1.1.39",
		zipball_url: "https://api.github.com/repos/oven-sh/bun/zipball/refs/tags/bun-v1.1.39",
		tarball_url: "https://api.github.com/repos/oven-sh/bun/tarball/refs/tags/bun-v1.1.39",
		commit: {
			sha: "1d4856170978abe3aa47960e2fd7d4f400423808",
			url: "https://api.github.com/repos/oven-sh/bun/commits/1d4856170978abe3aa47960e2fd7d4f400423808",
		},
		node_id: "MDM6UmVmMzU3NzI4OTY5OnJlZnMvdGFncy9idW4tdjEuMS4zOQ==",
	},
	{
		name: "bun-v1.1.38",
		zipball_url: "https://api.github.com/repos/oven-sh/bun/zipball/refs/tags/bun-v1.1.38",
		tarball_url: "https://api.github.com/repos/oven-sh/bun/tarball/refs/tags/bun-v1.1.38",
		commit: {
			sha: "bf2f153f5ca45876bc88369273743cd6fa04881c",
			url: "https://api.github.com/repos/oven-sh/bun/commits/bf2f153f5ca45876bc88369273743cd6fa04881c",
		},
		node_id: "MDM6UmVmMzU3NzI4OTY5OnJlZnMvdGFncy9idW4tdjEuMS4zOA==",
	},
	{
		name: "bun-v1.1.37",
		zipball_url: "https://api.github.com/repos/oven-sh/bun/zipball/refs/tags/bun-v1.1.37",
		tarball_url: "https://api.github.com/repos/oven-sh/bun/tarball/refs/tags/bun-v1.1.37",
		commit: {
			sha: "8ca0eb831d6739c6a94b3f4d484bbfe71ee97226",
			url: "https://api.github.com/repos/oven-sh/bun/commits/8ca0eb831d6739c6a94b3f4d484bbfe71ee97226",
		},
		node_id: "MDM6UmVmMzU3NzI4OTY5OnJlZnMvdGFncy9idW4tdjEuMS4zNw==",
	},
	{
		name: "bun-v1.1.36",
		zipball_url: "https://api.github.com/repos/oven-sh/bun/zipball/refs/tags/bun-v1.1.36",
		tarball_url: "https://api.github.com/repos/oven-sh/bun/tarball/refs/tags/bun-v1.1.36",
		commit: {
			sha: "ededc168cf07afcdbe5ca34495c58df435ea526d",
			url: "https://api.github.com/repos/oven-sh/bun/commits/ededc168cf07afcdbe5ca34495c58df435ea526d",
		},
		node_id: "MDM6UmVmMzU3NzI4OTY5OnJlZnMvdGFncy9idW4tdjEuMS4zNg==",
	},
	{
		name: "bun-v1.1.35",
		zipball_url: "https://api.github.com/repos/oven-sh/bun/zipball/refs/tags/bun-v1.1.35",
		tarball_url: "https://api.github.com/repos/oven-sh/bun/tarball/refs/tags/bun-v1.1.35",
		commit: {
			sha: "fc94db1efbf6d8cf97c2ec30aa4a3671f5717709",
			url: "https://api.github.com/repos/oven-sh/bun/commits/fc94db1efbf6d8cf97c2ec30aa4a3671f5717709",
		},
		node_id: "MDM6UmVmMzU3NzI4OTY5OnJlZnMvdGFncy9idW4tdjEuMS4zNQ==",
	},
	{
		name: "bun-v1.1.34",
		zipball_url: "https://api.github.com/repos/oven-sh/bun/zipball/refs/tags/bun-v1.1.34",
		tarball_url: "https://api.github.com/repos/oven-sh/bun/tarball/refs/tags/bun-v1.1.34",
		commit: {
			sha: "5e5e7c60f1004c79a3f87e1f5470ee19d57f10d0",
			url: "https://api.github.com/repos/oven-sh/bun/commits/5e5e7c60f1004c79a3f87e1f5470ee19d57f10d0",
		},
		node_id: "MDM6UmVmMzU3NzI4OTY5OnJlZnMvdGFncy9idW4tdjEuMS4zNA==",
	},
	{
		name: "bun-v1.1.33",
		zipball_url: "https://api.github.com/repos/oven-sh/bun/zipball/refs/tags/bun-v1.1.33",
		tarball_url: "https://api.github.com/repos/oven-sh/bun/tarball/refs/tags/bun-v1.1.33",
		commit: {
			sha: "247456b675d4bf4b9cd920e0a080b7002325c0df",
			url: "https://api.github.com/repos/oven-sh/bun/commits/247456b675d4bf4b9cd920e0a080b7002325c0df",
		},
		node_id: "MDM6UmVmMzU3NzI4OTY5OnJlZnMvdGFncy9idW4tdjEuMS4zMw==",
	},
	{
		name: "bun-v1.1.32",
		zipball_url: "https://api.github.com/repos/oven-sh/bun/zipball/refs/tags/bun-v1.1.32",
		tarball_url: "https://api.github.com/repos/oven-sh/bun/tarball/refs/tags/bun-v1.1.32",
		commit: {
			sha: "fe8d0079ecdfeb61cea6ba041ed6845d6fffa43e",
			url: "https://api.github.com/repos/oven-sh/bun/commits/fe8d0079ecdfeb61cea6ba041ed6845d6fffa43e",
		},
		node_id: "MDM6UmVmMzU3NzI4OTY5OnJlZnMvdGFncy9idW4tdjEuMS4zMg==",
	},
	{
		name: "bun-v1.1.31",
		zipball_url: "https://api.github.com/repos/oven-sh/bun/zipball/refs/tags/bun-v1.1.31",
		tarball_url: "https://api.github.com/repos/oven-sh/bun/tarball/refs/tags/bun-v1.1.31",
		commit: {
			sha: "e448c4cc3bf43fc67e39799d34c4ed70b8037509",
			url: "https://api.github.com/repos/oven-sh/bun/commits/e448c4cc3bf43fc67e39799d34c4ed70b8037509",
		},
		node_id: "MDM6UmVmMzU3NzI4OTY5OnJlZnMvdGFncy9idW4tdjEuMS4zMQ==",
	},
	{
		name: "bun-v1.1.30",
		zipball_url: "https://api.github.com/repos/oven-sh/bun/zipball/refs/tags/bun-v1.1.30",
		tarball_url: "https://api.github.com/repos/oven-sh/bun/tarball/refs/tags/bun-v1.1.30",
		commit: {
			sha: "7996d06b8f5869ccc9ad9a421cd06469da4273fc",
			url: "https://api.github.com/repos/oven-sh/bun/commits/7996d06b8f5869ccc9ad9a421cd06469da4273fc",
		},
		node_id: "MDM6UmVmMzU3NzI4OTY5OnJlZnMvdGFncy9idW4tdjEuMS4zMA==",
	},
	{
		name: "bun-v1.1.29",
		zipball_url: "https://api.github.com/repos/oven-sh/bun/zipball/refs/tags/bun-v1.1.29",
		tarball_url: "https://api.github.com/repos/oven-sh/bun/tarball/refs/tags/bun-v1.1.29",
		commit: {
			sha: "73c553b25ab06026acc628a95c5c65783f89e1e5",
			url: "https://api.github.com/repos/oven-sh/bun/commits/73c553b25ab06026acc628a95c5c65783f89e1e5",
		},
		node_id: "MDM6UmVmMzU3NzI4OTY5OnJlZnMvdGFncy9idW4tdjEuMS4yOQ==",
	},
	{
		name: "bun-v1.1.28",
		zipball_url: "https://api.github.com/repos/oven-sh/bun/zipball/refs/tags/bun-v1.1.28",
		tarball_url: "https://api.github.com/repos/oven-sh/bun/tarball/refs/tags/bun-v1.1.28",
		commit: {
			sha: "cf4e9cb69ee862037b09f2cd6668be76d2aca78d",
			url: "https://api.github.com/repos/oven-sh/bun/commits/cf4e9cb69ee862037b09f2cd6668be76d2aca78d",
		},
		node_id: "MDM6UmVmMzU3NzI4OTY5OnJlZnMvdGFncy9idW4tdjEuMS4yOA==",
	},
	{
		name: "bun-v1.1.27",
		zipball_url: "https://api.github.com/repos/oven-sh/bun/zipball/refs/tags/bun-v1.1.27",
		tarball_url: "https://api.github.com/repos/oven-sh/bun/tarball/refs/tags/bun-v1.1.27",
		commit: {
			sha: "267afa293483d5ed5f834a6d35350232188e3f98",
			url: "https://api.github.com/repos/oven-sh/bun/commits/267afa293483d5ed5f834a6d35350232188e3f98",
		},
		node_id: "MDM6UmVmMzU3NzI4OTY5OnJlZnMvdGFncy9idW4tdjEuMS4yNw==",
	},
	{
		name: "bun-v1.1.26",
		zipball_url: "https://api.github.com/repos/oven-sh/bun/zipball/refs/tags/bun-v1.1.26",
		tarball_url: "https://api.github.com/repos/oven-sh/bun/tarball/refs/tags/bun-v1.1.26",
		commit: {
			sha: "0a37423bafab6aebe803e5f1594cffa9796f2ae6",
			url: "https://api.github.com/repos/oven-sh/bun/commits/0a37423bafab6aebe803e5f1594cffa9796f2ae6",
		},
		node_id: "MDM6UmVmMzU3NzI4OTY5OnJlZnMvdGFncy9idW4tdjEuMS4yNg==",
	},
	{
		name: "bun-v1.1.25",
		zipball_url: "https://api.github.com/repos/oven-sh/bun/zipball/refs/tags/bun-v1.1.25",
		tarball_url: "https://api.github.com/repos/oven-sh/bun/tarball/refs/tags/bun-v1.1.25",
		commit: {
			sha: "fe62a614046948ebba260bed87db96287e67921f",
			url: "https://api.github.com/repos/oven-sh/bun/commits/fe62a614046948ebba260bed87db96287e67921f",
		},
		node_id: "MDM6UmVmMzU3NzI4OTY5OnJlZnMvdGFncy9idW4tdjEuMS4yNQ==",
	},
	{
		name: "bun-v1.1.24",
		zipball_url: "https://api.github.com/repos/oven-sh/bun/zipball/refs/tags/bun-v1.1.24",
		tarball_url: "https://api.github.com/repos/oven-sh/bun/tarball/refs/tags/bun-v1.1.24",
		commit: {
			sha: "85a32991152871b06becd6b411eb663008369769",
			url: "https://api.github.com/repos/oven-sh/bun/commits/85a32991152871b06becd6b411eb663008369769",
		},
		node_id: "MDM6UmVmMzU3NzI4OTY5OnJlZnMvdGFncy9idW4tdjEuMS4yNA==",
	},
	{
		name: "bun-v1.1.23",
		zipball_url: "https://api.github.com/repos/oven-sh/bun/zipball/refs/tags/bun-v1.1.23",
		tarball_url: "https://api.github.com/repos/oven-sh/bun/tarball/refs/tags/bun-v1.1.23",
		commit: {
			sha: "4304368fc00e4c46066c506dc50f37eaccab4f15",
			url: "https://api.github.com/repos/oven-sh/bun/commits/4304368fc00e4c46066c506dc50f37eaccab4f15",
		},
		node_id: "MDM6UmVmMzU3NzI4OTY5OnJlZnMvdGFncy9idW4tdjEuMS4yMw==",
	},
	{
		name: "bun-v1.1.22",
		zipball_url: "https://api.github.com/repos/oven-sh/bun/zipball/refs/tags/bun-v1.1.22",
		tarball_url: "https://api.github.com/repos/oven-sh/bun/tarball/refs/tags/bun-v1.1.22",
		commit: {
			sha: "d74a192345890e235b5e6dead080235c1917f44b",
			url: "https://api.github.com/repos/oven-sh/bun/commits/d74a192345890e235b5e6dead080235c1917f44b",
		},
		node_id: "MDM6UmVmMzU3NzI4OTY5OnJlZnMvdGFncy9idW4tdjEuMS4yMg==",
	},
	{
		name: "bun-v1.1.21",
		zipball_url: "https://api.github.com/repos/oven-sh/bun/zipball/refs/tags/bun-v1.1.21",
		tarball_url: "https://api.github.com/repos/oven-sh/bun/tarball/refs/tags/bun-v1.1.21",
		commit: {
			sha: "70ca2b76c3d33f7ceeea43a702b396ab8ffce25b",
			url: "https://api.github.com/repos/oven-sh/bun/commits/70ca2b76c3d33f7ceeea43a702b396ab8ffce25b",
		},
		node_id: "MDM6UmVmMzU3NzI4OTY5OnJlZnMvdGFncy9idW4tdjEuMS4yMQ==",
	},
	{
		name: "bun-v1.1.20",
		zipball_url: "https://api.github.com/repos/oven-sh/bun/zipball/refs/tags/bun-v1.1.20",
		tarball_url: "https://api.github.com/repos/oven-sh/bun/tarball/refs/tags/bun-v1.1.20",
		commit: {
			sha: "ae19489250ab74ee3ea7d5b50fca5d7d2b4e6d66",
			url: "https://api.github.com/repos/oven-sh/bun/commits/ae19489250ab74ee3ea7d5b50fca5d7d2b4e6d66",
		},
		node_id: "MDM6UmVmMzU3NzI4OTY5OnJlZnMvdGFncy9idW4tdjEuMS4yMA==",
	},
	{
		name: "bun-v1.1.19",
		zipball_url: "https://api.github.com/repos/oven-sh/bun/zipball/refs/tags/bun-v1.1.19",
		tarball_url: "https://api.github.com/repos/oven-sh/bun/tarball/refs/tags/bun-v1.1.19",
		commit: {
			sha: "110849355cdd640d4d2494a0d0e96375a69c7f72",
			url: "https://api.github.com/repos/oven-sh/bun/commits/110849355cdd640d4d2494a0d0e96375a69c7f72",
		},
		node_id: "MDM6UmVmMzU3NzI4OTY5OnJlZnMvdGFncy9idW4tdjEuMS4xOQ==",
	},
	{
		name: "bun-v1.1.18",
		zipball_url: "https://api.github.com/repos/oven-sh/bun/zipball/refs/tags/bun-v1.1.18",
		tarball_url: "https://api.github.com/repos/oven-sh/bun/tarball/refs/tags/bun-v1.1.18",
		commit: {
			sha: "5a0b93523134ca0043ee7ae84f01003aa4b7ff69",
			url: "https://api.github.com/repos/oven-sh/bun/commits/5a0b93523134ca0043ee7ae84f01003aa4b7ff69",
		},
		node_id: "MDM6UmVmMzU3NzI4OTY5OnJlZnMvdGFncy9idW4tdjEuMS4xOA==",
	},
	{
		name: "bun-v1.1.17",
		zipball_url: "https://api.github.com/repos/oven-sh/bun/zipball/refs/tags/bun-v1.1.17",
		tarball_url: "https://api.github.com/repos/oven-sh/bun/tarball/refs/tags/bun-v1.1.17",
		commit: {
			sha: "bb66bba1bf6d57983e7efef7ab706bce12137028",
			url: "https://api.github.com/repos/oven-sh/bun/commits/bb66bba1bf6d57983e7efef7ab706bce12137028",
		},
		node_id: "MDM6UmVmMzU3NzI4OTY5OnJlZnMvdGFncy9idW4tdjEuMS4xNw==",
	},
	{
		name: "bun-v1.1.16",
		zipball_url: "https://api.github.com/repos/oven-sh/bun/zipball/refs/tags/bun-v1.1.16",
		tarball_url: "https://api.github.com/repos/oven-sh/bun/tarball/refs/tags/bun-v1.1.16",
		commit: {
			sha: "bf7b327f68568104a5e40c1944b7b255b02f0745",
			url: "https://api.github.com/repos/oven-sh/bun/commits/bf7b327f68568104a5e40c1944b7b255b02f0745",
		},
		node_id: "MDM6UmVmMzU3NzI4OTY5OnJlZnMvdGFncy9idW4tdjEuMS4xNg==",
	},
	{
		name: "bun-v1.1.15",
		zipball_url: "https://api.github.com/repos/oven-sh/bun/zipball/refs/tags/bun-v1.1.15",
		tarball_url: "https://api.github.com/repos/oven-sh/bun/tarball/refs/tags/bun-v1.1.15",
		commit: {
			sha: "b23ba1fe1805891cdf4566331f0c8e87d0a5b758",
			url: "https://api.github.com/repos/oven-sh/bun/commits/b23ba1fe1805891cdf4566331f0c8e87d0a5b758",
		},
		node_id: "MDM6UmVmMzU3NzI4OTY5OnJlZnMvdGFncy9idW4tdjEuMS4xNQ==",
	},
	{
		name: "bun-v1.1.14",
		zipball_url: "https://api.github.com/repos/oven-sh/bun/zipball/refs/tags/bun-v1.1.14",
		tarball_url: "https://api.github.com/repos/oven-sh/bun/tarball/refs/tags/bun-v1.1.14",
		commit: {
			sha: "33ca0921f246487ff2f97d5bc3b36c7084725722",
			url: "https://api.github.com/repos/oven-sh/bun/commits/33ca0921f246487ff2f97d5bc3b36c7084725722",
		},
		node_id: "MDM6UmVmMzU3NzI4OTY5OnJlZnMvdGFncy9idW4tdjEuMS4xNA==",
	},
	{
		name: "bun-v1.1.13",
		zipball_url: "https://api.github.com/repos/oven-sh/bun/zipball/refs/tags/bun-v1.1.13",
		tarball_url: "https://api.github.com/repos/oven-sh/bun/tarball/refs/tags/bun-v1.1.13",
		commit: {
			sha: "bd6a6051203ff577240615ff4e242270035a36b7",
			url: "https://api.github.com/repos/oven-sh/bun/commits/bd6a6051203ff577240615ff4e242270035a36b7",
		},
		node_id: "MDM6UmVmMzU3NzI4OTY5OnJlZnMvdGFncy9idW4tdjEuMS4xMw==",
	},
	{
		name: "bun-v1.1.12",
		zipball_url: "https://api.github.com/repos/oven-sh/bun/zipball/refs/tags/bun-v1.1.12",
		tarball_url: "https://api.github.com/repos/oven-sh/bun/tarball/refs/tags/bun-v1.1.12",
		commit: {
			sha: "43f0913c3875cbf260c60868268adc5953b09a80",
			url: "https://api.github.com/repos/oven-sh/bun/commits/43f0913c3875cbf260c60868268adc5953b09a80",
		},
		node_id: "MDM6UmVmMzU3NzI4OTY5OnJlZnMvdGFncy9idW4tdjEuMS4xMg==",
	},
	{
		name: "bun-v1.1.11",
		zipball_url: "https://api.github.com/repos/oven-sh/bun/zipball/refs/tags/bun-v1.1.11",
		tarball_url: "https://api.github.com/repos/oven-sh/bun/tarball/refs/tags/bun-v1.1.11",
		commit: {
			sha: "4fb6056f85c9cf643caa9c2afdefe4917c513fb5",
			url: "https://api.github.com/repos/oven-sh/bun/commits/4fb6056f85c9cf643caa9c2afdefe4917c513fb5",
		},
		node_id: "MDM6UmVmMzU3NzI4OTY5OnJlZnMvdGFncy9idW4tdjEuMS4xMQ==",
	},
	{
		name: "bun-v1.1.10",
		zipball_url: "https://api.github.com/repos/oven-sh/bun/zipball/refs/tags/bun-v1.1.10",
		tarball_url: "https://api.github.com/repos/oven-sh/bun/tarball/refs/tags/bun-v1.1.10",
		commit: {
			sha: "5102a944307d56933a6bb039b99ad76a758b46e4",
			url: "https://api.github.com/repos/oven-sh/bun/commits/5102a944307d56933a6bb039b99ad76a758b46e4",
		},
		node_id: "MDM6UmVmMzU3NzI4OTY5OnJlZnMvdGFncy9idW4tdjEuMS4xMA==",
	},
	{
		name: "bun-v1.1.9",
		zipball_url: "https://api.github.com/repos/oven-sh/bun/zipball/refs/tags/bun-v1.1.9",
		tarball_url: "https://api.github.com/repos/oven-sh/bun/tarball/refs/tags/bun-v1.1.9",
		commit: {
			sha: "bb13798d9802d26770d8467a200022a2b91f7afd",
			url: "https://api.github.com/repos/oven-sh/bun/commits/bb13798d9802d26770d8467a200022a2b91f7afd",
		},
		node_id: "MDM6UmVmMzU3NzI4OTY5OnJlZnMvdGFncy9idW4tdjEuMS45",
	},
	{
		name: "bun-v1.1.8",
		zipball_url: "https://api.github.com/repos/oven-sh/bun/zipball/refs/tags/bun-v1.1.8",
		tarball_url: "https://api.github.com/repos/oven-sh/bun/tarball/refs/tags/bun-v1.1.8",
		commit: {
			sha: "89d25807fbf4488d3bfcb116484d0c2cf824f98c",
			url: "https://api.github.com/repos/oven-sh/bun/commits/89d25807fbf4488d3bfcb116484d0c2cf824f98c",
		},
		node_id: "MDM6UmVmMzU3NzI4OTY5OnJlZnMvdGFncy9idW4tdjEuMS44",
	},
	{
		name: "bun-v1.1.7",
		zipball_url: "https://api.github.com/repos/oven-sh/bun/zipball/refs/tags/bun-v1.1.7",
		tarball_url: "https://api.github.com/repos/oven-sh/bun/tarball/refs/tags/bun-v1.1.7",
		commit: {
			sha: "b0b7db5c060e830801b0273b7ff6e34e3eb5c254",
			url: "https://api.github.com/repos/oven-sh/bun/commits/b0b7db5c060e830801b0273b7ff6e34e3eb5c254",
		},
		node_id: "MDM6UmVmMzU3NzI4OTY5OnJlZnMvdGFncy9idW4tdjEuMS43",
	},
	{
		name: "bun-v1.1.6",
		zipball_url: "https://api.github.com/repos/oven-sh/bun/zipball/refs/tags/bun-v1.1.6",
		tarball_url: "https://api.github.com/repos/oven-sh/bun/tarball/refs/tags/bun-v1.1.6",
		commit: {
			sha: "84d81c3002bf68f913712b492a7aff988ad4c151",
			url: "https://api.github.com/repos/oven-sh/bun/commits/84d81c3002bf68f913712b492a7aff988ad4c151",
		},
		node_id: "MDM6UmVmMzU3NzI4OTY5OnJlZnMvdGFncy9idW4tdjEuMS42",
	},
	{
		name: "bun-v1.1.5",
		zipball_url: "https://api.github.com/repos/oven-sh/bun/zipball/refs/tags/bun-v1.1.5",
		tarball_url: "https://api.github.com/repos/oven-sh/bun/tarball/refs/tags/bun-v1.1.5",
		commit: {
			sha: "b257a309772db2e9dfb745f97068aea6a32ca151",
			url: "https://api.github.com/repos/oven-sh/bun/commits/b257a309772db2e9dfb745f97068aea6a32ca151",
		},
		node_id: "MDM6UmVmMzU3NzI4OTY5OnJlZnMvdGFncy9idW4tdjEuMS41",
	},
	{
		name: "bun-v1.1.4",
		zipball_url: "https://api.github.com/repos/oven-sh/bun/zipball/refs/tags/bun-v1.1.4",
		tarball_url: "https://api.github.com/repos/oven-sh/bun/tarball/refs/tags/bun-v1.1.4",
		commit: {
			sha: "fbe2fe0c3fd198530db51d9f54e0a03ffff9f22d",
			url: "https://api.github.com/repos/oven-sh/bun/commits/fbe2fe0c3fd198530db51d9f54e0a03ffff9f22d",
		},
		node_id: "MDM6UmVmMzU3NzI4OTY5OnJlZnMvdGFncy9idW4tdjEuMS40",
	},
	{
		name: "bun-v1.1.3",
		zipball_url: "https://api.github.com/repos/oven-sh/bun/zipball/refs/tags/bun-v1.1.3",
		tarball_url: "https://api.github.com/repos/oven-sh/bun/tarball/refs/tags/bun-v1.1.3",
		commit: {
			sha: "5baa2fbb87d1cb20a44ddb180c4b3a98ca70e95a",
			url: "https://api.github.com/repos/oven-sh/bun/commits/5baa2fbb87d1cb20a44ddb180c4b3a98ca70e95a",
		},
		node_id: "MDM6UmVmMzU3NzI4OTY5OnJlZnMvdGFncy9idW4tdjEuMS4z",
	},
	{
		name: "bun-v1.1.2",
		zipball_url: "https://api.github.com/repos/oven-sh/bun/zipball/refs/tags/bun-v1.1.2",
		tarball_url: "https://api.github.com/repos/oven-sh/bun/tarball/refs/tags/bun-v1.1.2",
		commit: {
			sha: "c8d072c2a978b93cb13ed7e5867abddb0e3177ec",
			url: "https://api.github.com/repos/oven-sh/bun/commits/c8d072c2a978b93cb13ed7e5867abddb0e3177ec",
		},
		node_id: "MDM6UmVmMzU3NzI4OTY5OnJlZnMvdGFncy9idW4tdjEuMS4y",
	},
	{
		name: "bun-v1.1.1",
		zipball_url: "https://api.github.com/repos/oven-sh/bun/zipball/refs/tags/bun-v1.1.1",
		tarball_url: "https://api.github.com/repos/oven-sh/bun/tarball/refs/tags/bun-v1.1.1",
		commit: {
			sha: "a09c421f2a112e018c4f04b63101af676b36fcd2",
			url: "https://api.github.com/repos/oven-sh/bun/commits/a09c421f2a112e018c4f04b63101af676b36fcd2",
		},
		node_id: "MDM6UmVmMzU3NzI4OTY5OnJlZnMvdGFncy9idW4tdjEuMS4x",
	},
	{
		name: "bun-v1.1.0",
		zipball_url: "https://api.github.com/repos/oven-sh/bun/zipball/refs/tags/bun-v1.1.0",
		tarball_url: "https://api.github.com/repos/oven-sh/bun/tarball/refs/tags/bun-v1.1.0",
		commit: {
			sha: "5903a614102704a627e6add42fc5668eb7acb68e",
			url: "https://api.github.com/repos/oven-sh/bun/commits/5903a614102704a627e6add42fc5668eb7acb68e",
		},
		node_id: "MDM6UmVmMzU3NzI4OTY5OnJlZnMvdGFncy9idW4tdjEuMS4w",
	},
	{
		name: "bun-v1.0.36",
		zipball_url: "https://api.github.com/repos/oven-sh/bun/zipball/refs/tags/bun-v1.0.36",
		tarball_url: "https://api.github.com/repos/oven-sh/bun/tarball/refs/tags/bun-v1.0.36",
		commit: {
			sha: "40f61ebb91e1bcf11672e820ecd7bf0af103c6fb",
			url: "https://api.github.com/repos/oven-sh/bun/commits/40f61ebb91e1bcf11672e820ecd7bf0af103c6fb",
		},
		node_id: "MDM6UmVmMzU3NzI4OTY5OnJlZnMvdGFncy9idW4tdjEuMC4zNg==",
	},
	{
		name: "bun-v1.0.35",
		zipball_url: "https://api.github.com/repos/oven-sh/bun/zipball/refs/tags/bun-v1.0.35",
		tarball_url: "https://api.github.com/repos/oven-sh/bun/tarball/refs/tags/bun-v1.0.35",
		commit: {
			sha: "940448d6b688faec123c6939e8117365625fa750",
			url: "https://api.github.com/repos/oven-sh/bun/commits/940448d6b688faec123c6939e8117365625fa750",
		},
		node_id: "MDM6UmVmMzU3NzI4OTY5OnJlZnMvdGFncy9idW4tdjEuMC4zNQ==",
	},
	{
		name: "bun-v1.0.34",
		zipball_url: "https://api.github.com/repos/oven-sh/bun/zipball/refs/tags/bun-v1.0.34",
		tarball_url: "https://api.github.com/repos/oven-sh/bun/tarball/refs/tags/bun-v1.0.34",
		commit: {
			sha: "f90bb7719b2c768307c8e4cc3a61429c11e2204b",
			url: "https://api.github.com/repos/oven-sh/bun/commits/f90bb7719b2c768307c8e4cc3a61429c11e2204b",
		},
		node_id: "MDM6UmVmMzU3NzI4OTY5OnJlZnMvdGFncy9idW4tdjEuMC4zNA==",
	},
	{
		name: "bun-v1.0.33",
		zipball_url: "https://api.github.com/repos/oven-sh/bun/zipball/refs/tags/bun-v1.0.33",
		tarball_url: "https://api.github.com/repos/oven-sh/bun/tarball/refs/tags/bun-v1.0.33",
		commit: {
			sha: "9e91e137f165a4f5c1be63beaba1a6650852a3b6",
			url: "https://api.github.com/repos/oven-sh/bun/commits/9e91e137f165a4f5c1be63beaba1a6650852a3b6",
		},
		node_id: "MDM6UmVmMzU3NzI4OTY5OnJlZnMvdGFncy9idW4tdjEuMC4zMw==",
	},
	{
		name: "bun-v1.0.32",
		zipball_url: "https://api.github.com/repos/oven-sh/bun/zipball/refs/tags/bun-v1.0.32",
		tarball_url: "https://api.github.com/repos/oven-sh/bun/tarball/refs/tags/bun-v1.0.32",
		commit: {
			sha: "5fec71bda456f214bbdec4d02763494e1c11c66b",
			url: "https://api.github.com/repos/oven-sh/bun/commits/5fec71bda456f214bbdec4d02763494e1c11c66b",
		},
		node_id: "MDM6UmVmMzU3NzI4OTY5OnJlZnMvdGFncy9idW4tdjEuMC4zMg==",
	},
	{
		name: "bun-v1.0.31",
		zipball_url: "https://api.github.com/repos/oven-sh/bun/zipball/refs/tags/bun-v1.0.31",
		tarball_url: "https://api.github.com/repos/oven-sh/bun/tarball/refs/tags/bun-v1.0.31",
		commit: {
			sha: "e2567512188b3d7e9926b8716767bebac9488619",
			url: "https://api.github.com/repos/oven-sh/bun/commits/e2567512188b3d7e9926b8716767bebac9488619",
		},
		node_id: "MDM6UmVmMzU3NzI4OTY5OnJlZnMvdGFncy9idW4tdjEuMC4zMQ==",
	},
	{
		name: "bun-v1.0.30",
		zipball_url: "https://api.github.com/repos/oven-sh/bun/zipball/refs/tags/bun-v1.0.30",
		tarball_url: "https://api.github.com/repos/oven-sh/bun/tarball/refs/tags/bun-v1.0.30",
		commit: {
			sha: "1424a196ffb8a6bace554070ef029913ec19e1da",
			url: "https://api.github.com/repos/oven-sh/bun/commits/1424a196ffb8a6bace554070ef029913ec19e1da",
		},
		node_id: "MDM6UmVmMzU3NzI4OTY5OnJlZnMvdGFncy9idW4tdjEuMC4zMA==",
	},
	{
		name: "bun-v1.0.29",
		zipball_url: "https://api.github.com/repos/oven-sh/bun/zipball/refs/tags/bun-v1.0.29",
		tarball_url: "https://api.github.com/repos/oven-sh/bun/tarball/refs/tags/bun-v1.0.29",
		commit: {
			sha: "094750cc9ccf3baafe62757951bad0d3741e4153",
			url: "https://api.github.com/repos/oven-sh/bun/commits/094750cc9ccf3baafe62757951bad0d3741e4153",
		},
		node_id: "MDM6UmVmMzU3NzI4OTY5OnJlZnMvdGFncy9idW4tdjEuMC4yOQ==",
	},
	{
		name: "bun-v1.0.28",
		zipball_url: "https://api.github.com/repos/oven-sh/bun/zipball/refs/tags/bun-v1.0.28",
		tarball_url: "https://api.github.com/repos/oven-sh/bun/tarball/refs/tags/bun-v1.0.28",
		commit: {
			sha: "7056384702231f634e4e5d0f7c65965041314fc6",
			url: "https://api.github.com/repos/oven-sh/bun/commits/7056384702231f634e4e5d0f7c65965041314fc6",
		},
		node_id: "MDM6UmVmMzU3NzI4OTY5OnJlZnMvdGFncy9idW4tdjEuMC4yOA==",
	},
	{
		name: "bun-v1.0.27",
		zipball_url: "https://api.github.com/repos/oven-sh/bun/zipball/refs/tags/bun-v1.0.27",
		tarball_url: "https://api.github.com/repos/oven-sh/bun/tarball/refs/tags/bun-v1.0.27",
		commit: {
			sha: "c34bbb2e3fcaaadd8dfb5e75d545acee1c3cfd1b",
			url: "https://api.github.com/repos/oven-sh/bun/commits/c34bbb2e3fcaaadd8dfb5e75d545acee1c3cfd1b",
		},
		node_id: "MDM6UmVmMzU3NzI4OTY5OnJlZnMvdGFncy9idW4tdjEuMC4yNw==",
	},
	{
		name: "bun-v1.0.26",
		zipball_url: "https://api.github.com/repos/oven-sh/bun/zipball/refs/tags/bun-v1.0.26",
		tarball_url: "https://api.github.com/repos/oven-sh/bun/tarball/refs/tags/bun-v1.0.26",
		commit: {
			sha: "c75e768a6ccc69380c1118b8d3d82249d5bfa102",
			url: "https://api.github.com/repos/oven-sh/bun/commits/c75e768a6ccc69380c1118b8d3d82249d5bfa102",
		},
		node_id: "MDM6UmVmMzU3NzI4OTY5OnJlZnMvdGFncy9idW4tdjEuMC4yNg==",
	},
	{
		name: "bun-v1.0.25",
		zipball_url: "https://api.github.com/repos/oven-sh/bun/zipball/refs/tags/bun-v1.0.25",
		tarball_url: "https://api.github.com/repos/oven-sh/bun/tarball/refs/tags/bun-v1.0.25",
		commit: {
			sha: "353f724a9cd12d1749e974e92bbc47d9138a6601",
			url: "https://api.github.com/repos/oven-sh/bun/commits/353f724a9cd12d1749e974e92bbc47d9138a6601",
		},
		node_id: "MDM6UmVmMzU3NzI4OTY5OnJlZnMvdGFncy9idW4tdjEuMC4yNQ==",
	},
] as const;
