// AUTO-GENERATED by lib/scripts/generate-defaults.mts — do not edit manually
import type { GitHubTag } from "../schemas/github.js";

export const denoDefaultTags: ReadonlyArray<GitHubTag> = [] as const;
