// AUTO-GENERATED by lib/scripts/generate-defaults.mts — do not edit manually
import type { RuntimeReleaseInput } from "../schemas/runtime-release.js";

export const denoDefaultInputs: ReadonlyArray<RuntimeReleaseInput> = [
	{
		version: "2.7.5",
		date: "2026-03-11T12:40:10Z",
	},
	{
		version: "2.7.4",
		date: "2026-03-05T14:21:56Z",
	},
	{
		version: "2.7.3",
		date: "2026-03-04T16:21:25Z",
	},
	{
		version: "2.7.2",
		date: "2026-03-03T16:06:30Z",
	},
	{
		version: "2.7.1",
		date: "2026-02-25T17:04:23Z",
	},
	{
		version: "2.7.0",
		date: "2026-02-25T10:39:21Z",
	},
	{
		version: "2.6.10",
		date: "2026-02-17T16:05:18Z",
	},
	{
		version: "2.6.9",
		date: "2026-02-10T17:22:03Z",
	},
	{
		version: "2.6.8",
		date: "2026-02-02T18:00:56Z",
	},
	{
		version: "2.6.7",
		date: "2026-01-29T14:12:59Z",
	},
	{
		version: "2.5.7",
		date: "2026-01-27T22:42:17Z",
	},
	{
		version: "2.6.6",
		date: "2026-01-22T22:23:20Z",
	},
	{
		version: "2.6.5",
		date: "2026-01-15T14:46:36Z",
	},
	{
		version: "2.6.4",
		date: "2026-01-05T19:22:16Z",
	},
	{
		version: "2.6.3",
		date: "2025-12-20T14:18:24Z",
	},
	{
		version: "2.6.2",
		date: "2025-12-19T16:52:25Z",
	},
	{
		version: "2.6.1",
		date: "2025-12-15T21:01:00Z",
	},
	{
		version: "2.6.0",
		date: "2025-12-10T17:00:44Z",
	},
	{
		version: "2.5.6",
		date: "2025-10-30T04:46:32Z",
	},
	{
		version: "2.5.5",
		date: "2025-10-28T20:12:45Z",
	},
	{
		version: "2.5.4",
		date: "2025-10-09T12:49:04Z",
	},
	{
		version: "2.5.3",
		date: "2025-10-03T04:39:49Z",
	},
	{
		version: "2.2.15",
		date: "2025-10-01T13:59:01Z",
	},
	{
		version: "2.1.14",
		date: "2025-09-29T23:11:52Z",
	},
	{
		version: "2.5.2",
		date: "2025-09-24T22:21:54Z",
	},
	{
		version: "2.5.1",
		date: "2025-09-17T07:22:39Z",
	},
	{
		version: "2.5.0",
		date: "2025-09-10T07:24:08Z",
	},
	{
		version: "2.4.5",
		date: "2025-08-21T14:44:19Z",
	},
	{
		version: "2.4.4",
		date: "2025-08-13T23:51:43Z",
	},
	{
		version: "2.4.3",
		date: "2025-07-31T05:20:45Z",
	},
	{
		version: "2.4.2",
		date: "2025-07-16T14:02:12Z",
	},
	{
		version: "2.2.14",
		date: "2025-07-16T11:45:32Z",
	},
	{
		version: "2.4.1",
		date: "2025-07-08T07:56:22Z",
	},
	{
		version: "2.4.0",
		date: "2025-07-01T22:07:43Z",
	},
	{
		version: "2.3.7",
		date: "2025-06-24T08:24:42Z",
	},
	{
		version: "2.3.6",
		date: "2025-06-12T14:26:34Z",
	},
	{
		version: "2.3.5",
		date: "2025-05-30T12:58:35Z",
	},
	{
		version: "2.3.4",
		date: "2025-05-30T00:14:49Z",
	},
	{
		version: "2.3.3",
		date: "2025-05-16T13:19:40Z",
	},
	{
		version: "2.3.2",
		date: "2025-05-16T01:03:46Z",
	},
	{
		version: "2.2.13",
		date: "2025-05-13T22:15:36Z",
	},
	{
		version: "2.1.13",
		date: "2025-05-13T22:15:10Z",
	},
	{
		version: "2.3.1",
		date: "2025-04-30T13:16:28Z",
	},
	{
		version: "2.3.0",
		date: "2025-04-30T09:43:29Z",
	},
	{
		version: "2.2.12",
		date: "2025-04-25T00:22:14Z",
	},
	{
		version: "2.2.11",
		date: "2025-04-18T15:20:09Z",
	},
	{
		version: "2.2.10",
		date: "2025-04-14T22:59:23Z",
	},
	{
		version: "2.2.9",
		date: "2025-04-11T21:13:57Z",
	},
	{
		version: "2.1.12",
		date: "2025-04-12T00:43:34Z",
	},
	{
		version: "2.1.11",
		date: "2025-04-10T13:45:03Z",
	},
	{
		version: "2.2.8",
		date: "2025-04-05T03:00:04Z",
	},
	{
		version: "2.2.7",
		date: "2025-04-04T10:43:48Z",
	},
	{
		version: "2.2.6",
		date: "2025-03-28T08:00:37Z",
	},
	{
		version: "2.2.5",
		date: "2025-03-21T12:10:52Z",
	},
	{
		version: "2.2.4",
		date: "2025-03-14T21:10:58Z",
	},
	{
		version: "2.2.3",
		date: "2025-03-05T05:28:57Z",
	},
	{
		version: "2.2.2",
		date: "2025-02-25T09:05:27Z",
	},
	{
		version: "2.2.1",
		date: "2025-02-21T01:04:42Z",
	},
	{
		version: "2.2.0",
		date: "2025-02-19T01:11:42Z",
	},
	{
		version: "2.1.10",
		date: "2025-02-13T07:48:31Z",
	},
	{
		version: "2.1.9",
		date: "2025-01-31T02:02:08Z",
	},
	{
		version: "2.1.8",
		date: "2025-01-30T19:35:12Z",
	},
	{
		version: "2.1.7",
		date: "2025-01-22T01:52:03Z",
	},
	{
		version: "2.1.6",
		date: "2025-01-17T01:55:48Z",
	},
	{
		version: "2.1.5",
		date: "2025-01-09T22:37:41Z",
	},
	{
		version: "2.1.4",
		date: "2024-12-11T12:07:33Z",
	},
	{
		version: "2.1.3",
		date: "2024-12-06T01:12:18Z",
	},
	{
		version: "2.1.2",
		date: "2024-11-28T17:22:39Z",
	},
	{
		version: "2.1.1",
		date: "2024-11-21T19:10:16Z",
	},
	{
		version: "2.1.0",
		date: "2024-11-21T04:12:24Z",
	},
	{
		version: "2.0.6",
		date: "2024-11-10T06:00:18Z",
	},
	{
		version: "2.0.5",
		date: "2024-11-06T01:47:00Z",
	},
	{
		version: "2.0.4",
		date: "2024-10-30T03:38:46Z",
	},
	{
		version: "2.0.3",
		date: "2024-10-25T12:54:07Z",
	},
	{
		version: "2.0.2",
		date: "2024-10-18T02:29:49Z",
	},
	{
		version: "2.0.1",
		date: "2024-10-17T01:14:48Z",
	},
	{
		version: "2.0.0",
		date: "2024-10-09T08:24:50Z",
	},
	{
		version: "1.46.3",
		date: "2024-09-04T16:28:15Z",
	},
	{
		version: "1.46.2",
		date: "2024-08-29T18:42:49Z",
	},
	{
		version: "1.46.1",
		date: "2024-08-22T16:24:08Z",
	},
	{
		version: "1.46.0",
		date: "2024-08-22T02:16:01Z",
	},
	{
		version: "1.45.5",
		date: "2024-07-31T22:06:35Z",
	},
	{
		version: "1.45.4",
		date: "2024-07-26T18:25:36Z",
	},
	{
		version: "1.45.3",
		date: "2024-07-23T01:48:24Z",
	},
	{
		version: "1.45.2",
		date: "2024-07-12T22:04:52Z",
	},
	{
		version: "1.45.1",
		date: "2024-07-11T23:12:35Z",
	},
	{
		version: "1.45.0",
		date: "2024-07-10T23:47:14Z",
	},
	{
		version: "1.44.4",
		date: "2024-06-19T18:27:34Z",
	},
	{
		version: "1.44.3",
		date: "2024-06-19T02:42:54Z",
	},
	{
		version: "1.44.2",
		date: "2024-06-13T03:41:38Z",
	},
	{
		version: "1.44.1",
		date: "2024-06-06T02:43:38Z",
	},
	{
		version: "1.44.0",
		date: "2024-05-30T07:51:14Z",
	},
	{
		version: "1.43.6",
		date: "2024-05-22T01:16:09Z",
	},
	{
		version: "1.43.5",
		date: "2024-05-18T01:42:45Z",
	},
	{
		version: "1.43.4",
		date: "2024-05-17T00:58:15Z",
	},
	{
		version: "1.43.3",
		date: "2024-05-10T23:18:45Z",
	},
	{
		version: "1.43.2",
		date: "2024-05-09T00:03:37Z",
	},
	{
		version: "1.43.1",
		date: "2024-05-01T21:45:40Z",
	},
	{
		version: "1.43.0",
		date: "2024-05-01T08:19:33Z",
	},
	{
		version: "1.42.4",
		date: "2024-04-16T01:46:33Z",
	},
] as const;
