// AUTO-GENERATED by lib/scripts/generate-defaults.mts — do not edit manually
import type { GitHubTag } from "../schemas/github.js";

export const denoDefaultTags: ReadonlyArray<GitHubTag> = [
	{
		name: "v2.7.4",
		zipball_url: "https://api.github.com/repos/denoland/deno/zipball/refs/tags/v2.7.4",
		tarball_url: "https://api.github.com/repos/denoland/deno/tarball/refs/tags/v2.7.4",
		commit: {
			sha: "8274bf758236405d50046dbe31beba96b6d3d2f6",
			url: "https://api.github.com/repos/denoland/deno/commits/8274bf758236405d50046dbe31beba96b6d3d2f6",
		},
		node_id: "MDM6UmVmMTMzNDQyMzg0OnJlZnMvdGFncy92Mi43LjQ=",
	},
	{
		name: "v2.7.3",
		zipball_url: "https://api.github.com/repos/denoland/deno/zipball/refs/tags/v2.7.3",
		tarball_url: "https://api.github.com/repos/denoland/deno/tarball/refs/tags/v2.7.3",
		commit: {
			sha: "e78a7fa8d86848a759e6743537cf90013c7160b1",
			url: "https://api.github.com/repos/denoland/deno/commits/e78a7fa8d86848a759e6743537cf90013c7160b1",
		},
		node_id: "MDM6UmVmMTMzNDQyMzg0OnJlZnMvdGFncy92Mi43LjM=",
	},
	{
		name: "v2.7.2",
		zipball_url: "https://api.github.com/repos/denoland/deno/zipball/refs/tags/v2.7.2",
		tarball_url: "https://api.github.com/repos/denoland/deno/tarball/refs/tags/v2.7.2",
		commit: {
			sha: "83e374686079a2f067115e60ad91ec38f4f6118b",
			url: "https://api.github.com/repos/denoland/deno/commits/83e374686079a2f067115e60ad91ec38f4f6118b",
		},
		node_id: "MDM6UmVmMTMzNDQyMzg0OnJlZnMvdGFncy92Mi43LjI=",
	},
	{
		name: "v2.7.1",
		zipball_url: "https://api.github.com/repos/denoland/deno/zipball/refs/tags/v2.7.1",
		tarball_url: "https://api.github.com/repos/denoland/deno/tarball/refs/tags/v2.7.1",
		commit: {
			sha: "1df618d969894353731981a17784816167ad82fb",
			url: "https://api.github.com/repos/denoland/deno/commits/1df618d969894353731981a17784816167ad82fb",
		},
		node_id: "MDM6UmVmMTMzNDQyMzg0OnJlZnMvdGFncy92Mi43LjE=",
	},
	{
		name: "v2.7.0",
		zipball_url: "https://api.github.com/repos/denoland/deno/zipball/refs/tags/v2.7.0",
		tarball_url: "https://api.github.com/repos/denoland/deno/tarball/refs/tags/v2.7.0",
		commit: {
			sha: "fb4db333c37ec1242a6f80738510d214018fea53",
			url: "https://api.github.com/repos/denoland/deno/commits/fb4db333c37ec1242a6f80738510d214018fea53",
		},
		node_id: "MDM6UmVmMTMzNDQyMzg0OnJlZnMvdGFncy92Mi43LjA=",
	},
	{
		name: "v2.6.10",
		zipball_url: "https://api.github.com/repos/denoland/deno/zipball/refs/tags/v2.6.10",
		tarball_url: "https://api.github.com/repos/denoland/deno/tarball/refs/tags/v2.6.10",
		commit: {
			sha: "8871ade7aa09eb907a04ee61a427f5ba14c54014",
			url: "https://api.github.com/repos/denoland/deno/commits/8871ade7aa09eb907a04ee61a427f5ba14c54014",
		},
		node_id: "MDM6UmVmMTMzNDQyMzg0OnJlZnMvdGFncy92Mi42LjEw",
	},
	{
		name: "v2.6.9",
		zipball_url: "https://api.github.com/repos/denoland/deno/zipball/refs/tags/v2.6.9",
		tarball_url: "https://api.github.com/repos/denoland/deno/tarball/refs/tags/v2.6.9",
		commit: {
			sha: "7a9888857e01c02417fd38144d4bf0ace73eb6ab",
			url: "https://api.github.com/repos/denoland/deno/commits/7a9888857e01c02417fd38144d4bf0ace73eb6ab",
		},
		node_id: "MDM6UmVmMTMzNDQyMzg0OnJlZnMvdGFncy92Mi42Ljk=",
	},
	{
		name: "v2.6.8",
		zipball_url: "https://api.github.com/repos/denoland/deno/zipball/refs/tags/v2.6.8",
		tarball_url: "https://api.github.com/repos/denoland/deno/tarball/refs/tags/v2.6.8",
		commit: {
			sha: "7ab62a769be154c0926fe8be640d48674eb79614",
			url: "https://api.github.com/repos/denoland/deno/commits/7ab62a769be154c0926fe8be640d48674eb79614",
		},
		node_id: "MDM6UmVmMTMzNDQyMzg0OnJlZnMvdGFncy92Mi42Ljg=",
	},
	{
		name: "v2.6.7",
		zipball_url: "https://api.github.com/repos/denoland/deno/zipball/refs/tags/v2.6.7",
		tarball_url: "https://api.github.com/repos/denoland/deno/tarball/refs/tags/v2.6.7",
		commit: {
			sha: "d155af667f0e57277dc992d1b9609d5e6712908d",
			url: "https://api.github.com/repos/denoland/deno/commits/d155af667f0e57277dc992d1b9609d5e6712908d",
		},
		node_id: "MDM6UmVmMTMzNDQyMzg0OnJlZnMvdGFncy92Mi42Ljc=",
	},
	{
		name: "v2.6.6",
		zipball_url: "https://api.github.com/repos/denoland/deno/zipball/refs/tags/v2.6.6",
		tarball_url: "https://api.github.com/repos/denoland/deno/tarball/refs/tags/v2.6.6",
		commit: {
			sha: "b9b87a6bfb61a5d8855ee1578620ac3a9393b6bb",
			url: "https://api.github.com/repos/denoland/deno/commits/b9b87a6bfb61a5d8855ee1578620ac3a9393b6bb",
		},
		node_id: "MDM6UmVmMTMzNDQyMzg0OnJlZnMvdGFncy92Mi42LjY=",
	},
	{
		name: "v2.6.5",
		zipball_url: "https://api.github.com/repos/denoland/deno/zipball/refs/tags/v2.6.5",
		tarball_url: "https://api.github.com/repos/denoland/deno/tarball/refs/tags/v2.6.5",
		commit: {
			sha: "c356d9a621fccad5047497238039cde10613b278",
			url: "https://api.github.com/repos/denoland/deno/commits/c356d9a621fccad5047497238039cde10613b278",
		},
		node_id: "MDM6UmVmMTMzNDQyMzg0OnJlZnMvdGFncy92Mi42LjU=",
	},
	{
		name: "v2.6.4",
		zipball_url: "https://api.github.com/repos/denoland/deno/zipball/refs/tags/v2.6.4",
		tarball_url: "https://api.github.com/repos/denoland/deno/tarball/refs/tags/v2.6.4",
		commit: {
			sha: "658638b3262a90c3e92fe96887fd898b5b1a78d7",
			url: "https://api.github.com/repos/denoland/deno/commits/658638b3262a90c3e92fe96887fd898b5b1a78d7",
		},
		node_id: "MDM6UmVmMTMzNDQyMzg0OnJlZnMvdGFncy92Mi42LjQ=",
	},
	{
		name: "v2.6.3",
		zipball_url: "https://api.github.com/repos/denoland/deno/zipball/refs/tags/v2.6.3",
		tarball_url: "https://api.github.com/repos/denoland/deno/tarball/refs/tags/v2.6.3",
		commit: {
			sha: "3fbb1daddbc9333cddf0d8c0735811717dd70f7a",
			url: "https://api.github.com/repos/denoland/deno/commits/3fbb1daddbc9333cddf0d8c0735811717dd70f7a",
		},
		node_id: "MDM6UmVmMTMzNDQyMzg0OnJlZnMvdGFncy92Mi42LjM=",
	},
	{
		name: "v2.6.2",
		zipball_url: "https://api.github.com/repos/denoland/deno/zipball/refs/tags/v2.6.2",
		tarball_url: "https://api.github.com/repos/denoland/deno/tarball/refs/tags/v2.6.2",
		commit: {
			sha: "9cd8077757a365f2e9e36499c2330d2d4facbb2e",
			url: "https://api.github.com/repos/denoland/deno/commits/9cd8077757a365f2e9e36499c2330d2d4facbb2e",
		},
		node_id: "MDM6UmVmMTMzNDQyMzg0OnJlZnMvdGFncy92Mi42LjI=",
	},
	{
		name: "v2.6.1",
		zipball_url: "https://api.github.com/repos/denoland/deno/zipball/refs/tags/v2.6.1",
		tarball_url: "https://api.github.com/repos/denoland/deno/tarball/refs/tags/v2.6.1",
		commit: {
			sha: "1ba09320aa4ef7362ec33ec332e6e6d38c75d2b5",
			url: "https://api.github.com/repos/denoland/deno/commits/1ba09320aa4ef7362ec33ec332e6e6d38c75d2b5",
		},
		node_id: "MDM6UmVmMTMzNDQyMzg0OnJlZnMvdGFncy92Mi42LjE=",
	},
	{
		name: "v2.6.0",
		zipball_url: "https://api.github.com/repos/denoland/deno/zipball/refs/tags/v2.6.0",
		tarball_url: "https://api.github.com/repos/denoland/deno/tarball/refs/tags/v2.6.0",
		commit: {
			sha: "d5b1548eba893d4cc26305f33739a6ca2e6e8c11",
			url: "https://api.github.com/repos/denoland/deno/commits/d5b1548eba893d4cc26305f33739a6ca2e6e8c11",
		},
		node_id: "MDM6UmVmMTMzNDQyMzg0OnJlZnMvdGFncy92Mi42LjA=",
	},
	{
		name: "v2.5.7",
		zipball_url: "https://api.github.com/repos/denoland/deno/zipball/refs/tags/v2.5.7",
		tarball_url: "https://api.github.com/repos/denoland/deno/tarball/refs/tags/v2.5.7",
		commit: {
			sha: "8533c169419c6c92069cb5981a73ee9c36d19798",
			url: "https://api.github.com/repos/denoland/deno/commits/8533c169419c6c92069cb5981a73ee9c36d19798",
		},
		node_id: "MDM6UmVmMTMzNDQyMzg0OnJlZnMvdGFncy92Mi41Ljc=",
	},
	{
		name: "v2.5.6",
		zipball_url: "https://api.github.com/repos/denoland/deno/zipball/refs/tags/v2.5.6",
		tarball_url: "https://api.github.com/repos/denoland/deno/tarball/refs/tags/v2.5.6",
		commit: {
			sha: "1b5f3112af364a3327b26f720746819c4f20f20d",
			url: "https://api.github.com/repos/denoland/deno/commits/1b5f3112af364a3327b26f720746819c4f20f20d",
		},
		node_id: "MDM6UmVmMTMzNDQyMzg0OnJlZnMvdGFncy92Mi41LjY=",
	},
	{
		name: "v2.5.5",
		zipball_url: "https://api.github.com/repos/denoland/deno/zipball/refs/tags/v2.5.5",
		tarball_url: "https://api.github.com/repos/denoland/deno/tarball/refs/tags/v2.5.5",
		commit: {
			sha: "367ecdd0360e935de0454c70e0018be61c02904e",
			url: "https://api.github.com/repos/denoland/deno/commits/367ecdd0360e935de0454c70e0018be61c02904e",
		},
		node_id: "MDM6UmVmMTMzNDQyMzg0OnJlZnMvdGFncy92Mi41LjU=",
	},
	{
		name: "v2.5.4",
		zipball_url: "https://api.github.com/repos/denoland/deno/zipball/refs/tags/v2.5.4",
		tarball_url: "https://api.github.com/repos/denoland/deno/tarball/refs/tags/v2.5.4",
		commit: {
			sha: "6fbce91e40cc07fc6da74068e5cc56fdd40f7b4c",
			url: "https://api.github.com/repos/denoland/deno/commits/6fbce91e40cc07fc6da74068e5cc56fdd40f7b4c",
		},
		node_id: "MDM6UmVmMTMzNDQyMzg0OnJlZnMvdGFncy92Mi41LjQ=",
	},
	{
		name: "v2.5.3",
		zipball_url: "https://api.github.com/repos/denoland/deno/zipball/refs/tags/v2.5.3",
		tarball_url: "https://api.github.com/repos/denoland/deno/tarball/refs/tags/v2.5.3",
		commit: {
			sha: "1c3d04cfaf50a4a0db7a1925c0a73af5ea89bc69",
			url: "https://api.github.com/repos/denoland/deno/commits/1c3d04cfaf50a4a0db7a1925c0a73af5ea89bc69",
		},
		node_id: "MDM6UmVmMTMzNDQyMzg0OnJlZnMvdGFncy92Mi41LjM=",
	},
	{
		name: "v2.5.2",
		zipball_url: "https://api.github.com/repos/denoland/deno/zipball/refs/tags/v2.5.2",
		tarball_url: "https://api.github.com/repos/denoland/deno/tarball/refs/tags/v2.5.2",
		commit: {
			sha: "02787156398518fdac51b1f633a8367f92a7d253",
			url: "https://api.github.com/repos/denoland/deno/commits/02787156398518fdac51b1f633a8367f92a7d253",
		},
		node_id: "MDM6UmVmMTMzNDQyMzg0OnJlZnMvdGFncy92Mi41LjI=",
	},
	{
		name: "v2.5.1",
		zipball_url: "https://api.github.com/repos/denoland/deno/zipball/refs/tags/v2.5.1",
		tarball_url: "https://api.github.com/repos/denoland/deno/tarball/refs/tags/v2.5.1",
		commit: {
			sha: "4c1cdfc9a4f3c8919d25d1b2fe01981025babec5",
			url: "https://api.github.com/repos/denoland/deno/commits/4c1cdfc9a4f3c8919d25d1b2fe01981025babec5",
		},
		node_id: "MDM6UmVmMTMzNDQyMzg0OnJlZnMvdGFncy92Mi41LjE=",
	},
	{
		name: "v2.5.0",
		zipball_url: "https://api.github.com/repos/denoland/deno/zipball/refs/tags/v2.5.0",
		tarball_url: "https://api.github.com/repos/denoland/deno/tarball/refs/tags/v2.5.0",
		commit: {
			sha: "c6adba122836aeddd92800c45282897e1f508bd3",
			url: "https://api.github.com/repos/denoland/deno/commits/c6adba122836aeddd92800c45282897e1f508bd3",
		},
		node_id: "MDM6UmVmMTMzNDQyMzg0OnJlZnMvdGFncy92Mi41LjA=",
	},
	{
		name: "v2.4.5",
		zipball_url: "https://api.github.com/repos/denoland/deno/zipball/refs/tags/v2.4.5",
		tarball_url: "https://api.github.com/repos/denoland/deno/tarball/refs/tags/v2.4.5",
		commit: {
			sha: "b7061b0f64b3c79b312de5a59122b7184b2fdef2",
			url: "https://api.github.com/repos/denoland/deno/commits/b7061b0f64b3c79b312de5a59122b7184b2fdef2",
		},
		node_id: "MDM6UmVmMTMzNDQyMzg0OnJlZnMvdGFncy92Mi40LjU=",
	},
	{
		name: "v2.4.4",
		zipball_url: "https://api.github.com/repos/denoland/deno/zipball/refs/tags/v2.4.4",
		tarball_url: "https://api.github.com/repos/denoland/deno/tarball/refs/tags/v2.4.4",
		commit: {
			sha: "5129d036ebd51b229adb7579e2c805859e3f95c0",
			url: "https://api.github.com/repos/denoland/deno/commits/5129d036ebd51b229adb7579e2c805859e3f95c0",
		},
		node_id: "MDM6UmVmMTMzNDQyMzg0OnJlZnMvdGFncy92Mi40LjQ=",
	},
	{
		name: "v2.4.3",
		zipball_url: "https://api.github.com/repos/denoland/deno/zipball/refs/tags/v2.4.3",
		tarball_url: "https://api.github.com/repos/denoland/deno/tarball/refs/tags/v2.4.3",
		commit: {
			sha: "5612d2edc7262d7bfb3bcfb0f18649b01ec94b53",
			url: "https://api.github.com/repos/denoland/deno/commits/5612d2edc7262d7bfb3bcfb0f18649b01ec94b53",
		},
		node_id: "MDM6UmVmMTMzNDQyMzg0OnJlZnMvdGFncy92Mi40LjM=",
	},
	{
		name: "v2.4.2",
		zipball_url: "https://api.github.com/repos/denoland/deno/zipball/refs/tags/v2.4.2",
		tarball_url: "https://api.github.com/repos/denoland/deno/tarball/refs/tags/v2.4.2",
		commit: {
			sha: "622c3513936c1614ee316516a31343729c3c4367",
			url: "https://api.github.com/repos/denoland/deno/commits/622c3513936c1614ee316516a31343729c3c4367",
		},
		node_id: "MDM6UmVmMTMzNDQyMzg0OnJlZnMvdGFncy92Mi40LjI=",
	},
	{
		name: "v2.4.1",
		zipball_url: "https://api.github.com/repos/denoland/deno/zipball/refs/tags/v2.4.1",
		tarball_url: "https://api.github.com/repos/denoland/deno/tarball/refs/tags/v2.4.1",
		commit: {
			sha: "c03199ea1e4e22d44aad0deafc634be82e5b841b",
			url: "https://api.github.com/repos/denoland/deno/commits/c03199ea1e4e22d44aad0deafc634be82e5b841b",
		},
		node_id: "MDM6UmVmMTMzNDQyMzg0OnJlZnMvdGFncy92Mi40LjE=",
	},
	{
		name: "v2.4.0",
		zipball_url: "https://api.github.com/repos/denoland/deno/zipball/refs/tags/v2.4.0",
		tarball_url: "https://api.github.com/repos/denoland/deno/tarball/refs/tags/v2.4.0",
		commit: {
			sha: "45dfae18eec45c91146231aa05f4b249378691b5",
			url: "https://api.github.com/repos/denoland/deno/commits/45dfae18eec45c91146231aa05f4b249378691b5",
		},
		node_id: "MDM6UmVmMTMzNDQyMzg0OnJlZnMvdGFncy92Mi40LjA=",
	},
	{
		name: "v2.3.7",
		zipball_url: "https://api.github.com/repos/denoland/deno/zipball/refs/tags/v2.3.7",
		tarball_url: "https://api.github.com/repos/denoland/deno/tarball/refs/tags/v2.3.7",
		commit: {
			sha: "0d76cd50af2b21e0ac772bb5219199e32a8f312d",
			url: "https://api.github.com/repos/denoland/deno/commits/0d76cd50af2b21e0ac772bb5219199e32a8f312d",
		},
		node_id: "MDM6UmVmMTMzNDQyMzg0OnJlZnMvdGFncy92Mi4zLjc=",
	},
	{
		name: "v2.3.6",
		zipball_url: "https://api.github.com/repos/denoland/deno/zipball/refs/tags/v2.3.6",
		tarball_url: "https://api.github.com/repos/denoland/deno/tarball/refs/tags/v2.3.6",
		commit: {
			sha: "d2d8d3775fe0fbb34de08421f612ded43dea4473",
			url: "https://api.github.com/repos/denoland/deno/commits/d2d8d3775fe0fbb34de08421f612ded43dea4473",
		},
		node_id: "MDM6UmVmMTMzNDQyMzg0OnJlZnMvdGFncy92Mi4zLjY=",
	},
	{
		name: "v2.3.5",
		zipball_url: "https://api.github.com/repos/denoland/deno/zipball/refs/tags/v2.3.5",
		tarball_url: "https://api.github.com/repos/denoland/deno/tarball/refs/tags/v2.3.5",
		commit: {
			sha: "4794dc147e51c75cfa501d39da72cbd0ecb9b068",
			url: "https://api.github.com/repos/denoland/deno/commits/4794dc147e51c75cfa501d39da72cbd0ecb9b068",
		},
		node_id: "MDM6UmVmMTMzNDQyMzg0OnJlZnMvdGFncy92Mi4zLjU=",
	},
	{
		name: "v2.3.4",
		zipball_url: "https://api.github.com/repos/denoland/deno/zipball/refs/tags/v2.3.4",
		tarball_url: "https://api.github.com/repos/denoland/deno/tarball/refs/tags/v2.3.4",
		commit: {
			sha: "37ba6223b6733c4b18d4727c23f6831558c0ccc8",
			url: "https://api.github.com/repos/denoland/deno/commits/37ba6223b6733c4b18d4727c23f6831558c0ccc8",
		},
		node_id: "MDM6UmVmMTMzNDQyMzg0OnJlZnMvdGFncy92Mi4zLjQ=",
	},
	{
		name: "v2.3.3",
		zipball_url: "https://api.github.com/repos/denoland/deno/zipball/refs/tags/v2.3.3",
		tarball_url: "https://api.github.com/repos/denoland/deno/tarball/refs/tags/v2.3.3",
		commit: {
			sha: "395878c5fb72d87a44f7c88ce9f391acc31feab3",
			url: "https://api.github.com/repos/denoland/deno/commits/395878c5fb72d87a44f7c88ce9f391acc31feab3",
		},
		node_id: "MDM6UmVmMTMzNDQyMzg0OnJlZnMvdGFncy92Mi4zLjM=",
	},
	{
		name: "v2.3.2",
		zipball_url: "https://api.github.com/repos/denoland/deno/zipball/refs/tags/v2.3.2",
		tarball_url: "https://api.github.com/repos/denoland/deno/tarball/refs/tags/v2.3.2",
		commit: {
			sha: "7b74f385396bded16f99db64b97aa48e6f603f16",
			url: "https://api.github.com/repos/denoland/deno/commits/7b74f385396bded16f99db64b97aa48e6f603f16",
		},
		node_id: "MDM6UmVmMTMzNDQyMzg0OnJlZnMvdGFncy92Mi4zLjI=",
	},
	{
		name: "v2.3.1",
		zipball_url: "https://api.github.com/repos/denoland/deno/zipball/refs/tags/v2.3.1",
		tarball_url: "https://api.github.com/repos/denoland/deno/tarball/refs/tags/v2.3.1",
		commit: {
			sha: "8773b5f5b074e1e374a403d05943b6a7bbbdebad",
			url: "https://api.github.com/repos/denoland/deno/commits/8773b5f5b074e1e374a403d05943b6a7bbbdebad",
		},
		node_id: "MDM6UmVmMTMzNDQyMzg0OnJlZnMvdGFncy92Mi4zLjE=",
	},
	{
		name: "v2.3.0",
		zipball_url: "https://api.github.com/repos/denoland/deno/zipball/refs/tags/v2.3.0",
		tarball_url: "https://api.github.com/repos/denoland/deno/tarball/refs/tags/v2.3.0",
		commit: {
			sha: "61574bb9c9c255d5c661add6c7464af30475c197",
			url: "https://api.github.com/repos/denoland/deno/commits/61574bb9c9c255d5c661add6c7464af30475c197",
		},
		node_id: "MDM6UmVmMTMzNDQyMzg0OnJlZnMvdGFncy92Mi4zLjA=",
	},
	{
		name: "v2.2.15",
		zipball_url: "https://api.github.com/repos/denoland/deno/zipball/refs/tags/v2.2.15",
		tarball_url: "https://api.github.com/repos/denoland/deno/tarball/refs/tags/v2.2.15",
		commit: {
			sha: "5f6b1329dfd377ff03a389fb32faf73bb966e81d",
			url: "https://api.github.com/repos/denoland/deno/commits/5f6b1329dfd377ff03a389fb32faf73bb966e81d",
		},
		node_id: "MDM6UmVmMTMzNDQyMzg0OnJlZnMvdGFncy92Mi4yLjE1",
	},
	{
		name: "v2.2.14",
		zipball_url: "https://api.github.com/repos/denoland/deno/zipball/refs/tags/v2.2.14",
		tarball_url: "https://api.github.com/repos/denoland/deno/tarball/refs/tags/v2.2.14",
		commit: {
			sha: "ec5368efefd1fbdfe0c83a20237b5117d1291c11",
			url: "https://api.github.com/repos/denoland/deno/commits/ec5368efefd1fbdfe0c83a20237b5117d1291c11",
		},
		node_id: "MDM6UmVmMTMzNDQyMzg0OnJlZnMvdGFncy92Mi4yLjE0",
	},
	{
		name: "v2.2.13",
		zipball_url: "https://api.github.com/repos/denoland/deno/zipball/refs/tags/v2.2.13",
		tarball_url: "https://api.github.com/repos/denoland/deno/tarball/refs/tags/v2.2.13",
		commit: {
			sha: "0117f27aef98e1bf9a8689fe5ab6b03b5a1453f7",
			url: "https://api.github.com/repos/denoland/deno/commits/0117f27aef98e1bf9a8689fe5ab6b03b5a1453f7",
		},
		node_id: "MDM6UmVmMTMzNDQyMzg0OnJlZnMvdGFncy92Mi4yLjEz",
	},
	{
		name: "v2.2.12",
		zipball_url: "https://api.github.com/repos/denoland/deno/zipball/refs/tags/v2.2.12",
		tarball_url: "https://api.github.com/repos/denoland/deno/tarball/refs/tags/v2.2.12",
		commit: {
			sha: "81da8139af85a0cb7efa9050ae6b5461b3614077",
			url: "https://api.github.com/repos/denoland/deno/commits/81da8139af85a0cb7efa9050ae6b5461b3614077",
		},
		node_id: "MDM6UmVmMTMzNDQyMzg0OnJlZnMvdGFncy92Mi4yLjEy",
	},
	{
		name: "v2.2.11",
		zipball_url: "https://api.github.com/repos/denoland/deno/zipball/refs/tags/v2.2.11",
		tarball_url: "https://api.github.com/repos/denoland/deno/tarball/refs/tags/v2.2.11",
		commit: {
			sha: "225fbd59bf9a1d50603adb99fe2748edf70b9de2",
			url: "https://api.github.com/repos/denoland/deno/commits/225fbd59bf9a1d50603adb99fe2748edf70b9de2",
		},
		node_id: "MDM6UmVmMTMzNDQyMzg0OnJlZnMvdGFncy92Mi4yLjEx",
	},
	{
		name: "v2.2.10",
		zipball_url: "https://api.github.com/repos/denoland/deno/zipball/refs/tags/v2.2.10",
		tarball_url: "https://api.github.com/repos/denoland/deno/tarball/refs/tags/v2.2.10",
		commit: {
			sha: "adc34a6b3b8f6ff593810c0655d0d1a4b7ea3729",
			url: "https://api.github.com/repos/denoland/deno/commits/adc34a6b3b8f6ff593810c0655d0d1a4b7ea3729",
		},
		node_id: "MDM6UmVmMTMzNDQyMzg0OnJlZnMvdGFncy92Mi4yLjEw",
	},
	{
		name: "v2.2.9",
		zipball_url: "https://api.github.com/repos/denoland/deno/zipball/refs/tags/v2.2.9",
		tarball_url: "https://api.github.com/repos/denoland/deno/tarball/refs/tags/v2.2.9",
		commit: {
			sha: "25defa74d539d1d6fd27ddabd5260705677c43e8",
			url: "https://api.github.com/repos/denoland/deno/commits/25defa74d539d1d6fd27ddabd5260705677c43e8",
		},
		node_id: "MDM6UmVmMTMzNDQyMzg0OnJlZnMvdGFncy92Mi4yLjk=",
	},
	{
		name: "v2.2.8",
		zipball_url: "https://api.github.com/repos/denoland/deno/zipball/refs/tags/v2.2.8",
		tarball_url: "https://api.github.com/repos/denoland/deno/tarball/refs/tags/v2.2.8",
		commit: {
			sha: "32b9cc91d8c343bdec2ddcf3cedb27b5efc2f5e4",
			url: "https://api.github.com/repos/denoland/deno/commits/32b9cc91d8c343bdec2ddcf3cedb27b5efc2f5e4",
		},
		node_id: "MDM6UmVmMTMzNDQyMzg0OnJlZnMvdGFncy92Mi4yLjg=",
	},
	{
		name: "v2.2.7",
		zipball_url: "https://api.github.com/repos/denoland/deno/zipball/refs/tags/v2.2.7",
		tarball_url: "https://api.github.com/repos/denoland/deno/tarball/refs/tags/v2.2.7",
		commit: {
			sha: "e7dab411533fd7240fd794398ba9d9590e28f69d",
			url: "https://api.github.com/repos/denoland/deno/commits/e7dab411533fd7240fd794398ba9d9590e28f69d",
		},
		node_id: "MDM6UmVmMTMzNDQyMzg0OnJlZnMvdGFncy92Mi4yLjc=",
	},
	{
		name: "v2.2.6",
		zipball_url: "https://api.github.com/repos/denoland/deno/zipball/refs/tags/v2.2.6",
		tarball_url: "https://api.github.com/repos/denoland/deno/tarball/refs/tags/v2.2.6",
		commit: {
			sha: "2037200c4bc903162cd16b71b2564ab5bcd0601e",
			url: "https://api.github.com/repos/denoland/deno/commits/2037200c4bc903162cd16b71b2564ab5bcd0601e",
		},
		node_id: "MDM6UmVmMTMzNDQyMzg0OnJlZnMvdGFncy92Mi4yLjY=",
	},
	{
		name: "v2.2.5",
		zipball_url: "https://api.github.com/repos/denoland/deno/zipball/refs/tags/v2.2.5",
		tarball_url: "https://api.github.com/repos/denoland/deno/tarball/refs/tags/v2.2.5",
		commit: {
			sha: "6e08a9d2291cf45ae4031e163b8c1a03a0e85983",
			url: "https://api.github.com/repos/denoland/deno/commits/6e08a9d2291cf45ae4031e163b8c1a03a0e85983",
		},
		node_id: "MDM6UmVmMTMzNDQyMzg0OnJlZnMvdGFncy92Mi4yLjU=",
	},
	{
		name: "v2.2.4",
		zipball_url: "https://api.github.com/repos/denoland/deno/zipball/refs/tags/v2.2.4",
		tarball_url: "https://api.github.com/repos/denoland/deno/tarball/refs/tags/v2.2.4",
		commit: {
			sha: "33132abbd9ee0defa4bf0332c4797ee4341a03fc",
			url: "https://api.github.com/repos/denoland/deno/commits/33132abbd9ee0defa4bf0332c4797ee4341a03fc",
		},
		node_id: "MDM6UmVmMTMzNDQyMzg0OnJlZnMvdGFncy92Mi4yLjQ=",
	},
	{
		name: "v2.2.3",
		zipball_url: "https://api.github.com/repos/denoland/deno/zipball/refs/tags/v2.2.3",
		tarball_url: "https://api.github.com/repos/denoland/deno/tarball/refs/tags/v2.2.3",
		commit: {
			sha: "8203278401f4ffcb477a28b3ae9b915d88de7dd7",
			url: "https://api.github.com/repos/denoland/deno/commits/8203278401f4ffcb477a28b3ae9b915d88de7dd7",
		},
		node_id: "MDM6UmVmMTMzNDQyMzg0OnJlZnMvdGFncy92Mi4yLjM=",
	},
	{
		name: "v2.2.2",
		zipball_url: "https://api.github.com/repos/denoland/deno/zipball/refs/tags/v2.2.2",
		tarball_url: "https://api.github.com/repos/denoland/deno/tarball/refs/tags/v2.2.2",
		commit: {
			sha: "b2e5efd3826974857f4e5a94d87c2c724fa5bf5d",
			url: "https://api.github.com/repos/denoland/deno/commits/b2e5efd3826974857f4e5a94d87c2c724fa5bf5d",
		},
		node_id: "MDM6UmVmMTMzNDQyMzg0OnJlZnMvdGFncy92Mi4yLjI=",
	},
	{
		name: "v2.2.1",
		zipball_url: "https://api.github.com/repos/denoland/deno/zipball/refs/tags/v2.2.1",
		tarball_url: "https://api.github.com/repos/denoland/deno/tarball/refs/tags/v2.2.1",
		commit: {
			sha: "6057bc30da1df2b247f584b5280e1f10c02eec75",
			url: "https://api.github.com/repos/denoland/deno/commits/6057bc30da1df2b247f584b5280e1f10c02eec75",
		},
		node_id: "MDM6UmVmMTMzNDQyMzg0OnJlZnMvdGFncy92Mi4yLjE=",
	},
	{
		name: "v2.2.0",
		zipball_url: "https://api.github.com/repos/denoland/deno/zipball/refs/tags/v2.2.0",
		tarball_url: "https://api.github.com/repos/denoland/deno/tarball/refs/tags/v2.2.0",
		commit: {
			sha: "29688168631edb677a444ba3cd02b2be21304a1f",
			url: "https://api.github.com/repos/denoland/deno/commits/29688168631edb677a444ba3cd02b2be21304a1f",
		},
		node_id: "MDM6UmVmMTMzNDQyMzg0OnJlZnMvdGFncy92Mi4yLjA=",
	},
	{
		name: "v2.1.14",
		zipball_url: "https://api.github.com/repos/denoland/deno/zipball/refs/tags/v2.1.14",
		tarball_url: "https://api.github.com/repos/denoland/deno/tarball/refs/tags/v2.1.14",
		commit: {
			sha: "b8ae1323051c14a66a1c88434aa0f1e49f960c10",
			url: "https://api.github.com/repos/denoland/deno/commits/b8ae1323051c14a66a1c88434aa0f1e49f960c10",
		},
		node_id: "MDM6UmVmMTMzNDQyMzg0OnJlZnMvdGFncy92Mi4xLjE0",
	},
	{
		name: "v2.1.13",
		zipball_url: "https://api.github.com/repos/denoland/deno/zipball/refs/tags/v2.1.13",
		tarball_url: "https://api.github.com/repos/denoland/deno/tarball/refs/tags/v2.1.13",
		commit: {
			sha: "5b85bdaf88e36a1fcae3e442d96f026e4e1f9b92",
			url: "https://api.github.com/repos/denoland/deno/commits/5b85bdaf88e36a1fcae3e442d96f026e4e1f9b92",
		},
		node_id: "MDM6UmVmMTMzNDQyMzg0OnJlZnMvdGFncy92Mi4xLjEz",
	},
	{
		name: "v2.1.12",
		zipball_url: "https://api.github.com/repos/denoland/deno/zipball/refs/tags/v2.1.12",
		tarball_url: "https://api.github.com/repos/denoland/deno/tarball/refs/tags/v2.1.12",
		commit: {
			sha: "16b18e2b8dddde755364b740d63aa7da3646b33c",
			url: "https://api.github.com/repos/denoland/deno/commits/16b18e2b8dddde755364b740d63aa7da3646b33c",
		},
		node_id: "MDM6UmVmMTMzNDQyMzg0OnJlZnMvdGFncy92Mi4xLjEy",
	},
	{
		name: "v2.1.11",
		zipball_url: "https://api.github.com/repos/denoland/deno/zipball/refs/tags/v2.1.11",
		tarball_url: "https://api.github.com/repos/denoland/deno/tarball/refs/tags/v2.1.11",
		commit: {
			sha: "d73d467148cff810ccf9c96bed9bcaf32ce5281c",
			url: "https://api.github.com/repos/denoland/deno/commits/d73d467148cff810ccf9c96bed9bcaf32ce5281c",
		},
		node_id: "MDM6UmVmMTMzNDQyMzg0OnJlZnMvdGFncy92Mi4xLjEx",
	},
	{
		name: "v2.1.10",
		zipball_url: "https://api.github.com/repos/denoland/deno/zipball/refs/tags/v2.1.10",
		tarball_url: "https://api.github.com/repos/denoland/deno/tarball/refs/tags/v2.1.10",
		commit: {
			sha: "073e0879791486f70c7ac99d2d100c3fca6ac461",
			url: "https://api.github.com/repos/denoland/deno/commits/073e0879791486f70c7ac99d2d100c3fca6ac461",
		},
		node_id: "MDM6UmVmMTMzNDQyMzg0OnJlZnMvdGFncy92Mi4xLjEw",
	},
	{
		name: "v2.1.9",
		zipball_url: "https://api.github.com/repos/denoland/deno/zipball/refs/tags/v2.1.9",
		tarball_url: "https://api.github.com/repos/denoland/deno/tarball/refs/tags/v2.1.9",
		commit: {
			sha: "46e2f9a47ee5293547efd089438db29690a05f85",
			url: "https://api.github.com/repos/denoland/deno/commits/46e2f9a47ee5293547efd089438db29690a05f85",
		},
		node_id: "MDM6UmVmMTMzNDQyMzg0OnJlZnMvdGFncy92Mi4xLjk=",
	},
	{
		name: "v2.1.8",
		zipball_url: "https://api.github.com/repos/denoland/deno/zipball/refs/tags/v2.1.8",
		tarball_url: "https://api.github.com/repos/denoland/deno/tarball/refs/tags/v2.1.8",
		commit: {
			sha: "318646f7678111d24b139f4c589a4ef447c8cf1c",
			url: "https://api.github.com/repos/denoland/deno/commits/318646f7678111d24b139f4c589a4ef447c8cf1c",
		},
		node_id: "MDM6UmVmMTMzNDQyMzg0OnJlZnMvdGFncy92Mi4xLjg=",
	},
	{
		name: "v2.1.7",
		zipball_url: "https://api.github.com/repos/denoland/deno/zipball/refs/tags/v2.1.7",
		tarball_url: "https://api.github.com/repos/denoland/deno/tarball/refs/tags/v2.1.7",
		commit: {
			sha: "379079d9049499af660b70423aa7cc3aca0d5e52",
			url: "https://api.github.com/repos/denoland/deno/commits/379079d9049499af660b70423aa7cc3aca0d5e52",
		},
		node_id: "MDM6UmVmMTMzNDQyMzg0OnJlZnMvdGFncy92Mi4xLjc=",
	},
	{
		name: "v2.1.6",
		zipball_url: "https://api.github.com/repos/denoland/deno/zipball/refs/tags/v2.1.6",
		tarball_url: "https://api.github.com/repos/denoland/deno/tarball/refs/tags/v2.1.6",
		commit: {
			sha: "4ee86d8d125c7b36570e87f0725eb82b6fe4a4b4",
			url: "https://api.github.com/repos/denoland/deno/commits/4ee86d8d125c7b36570e87f0725eb82b6fe4a4b4",
		},
		node_id: "MDM6UmVmMTMzNDQyMzg0OnJlZnMvdGFncy92Mi4xLjY=",
	},
	{
		name: "v2.1.5",
		zipball_url: "https://api.github.com/repos/denoland/deno/zipball/refs/tags/v2.1.5",
		tarball_url: "https://api.github.com/repos/denoland/deno/tarball/refs/tags/v2.1.5",
		commit: {
			sha: "d15a95e28b0ec015c2f2a88cca3882ba96d5da98",
			url: "https://api.github.com/repos/denoland/deno/commits/d15a95e28b0ec015c2f2a88cca3882ba96d5da98",
		},
		node_id: "MDM6UmVmMTMzNDQyMzg0OnJlZnMvdGFncy92Mi4xLjU=",
	},
	{
		name: "v2.1.4",
		zipball_url: "https://api.github.com/repos/denoland/deno/zipball/refs/tags/v2.1.4",
		tarball_url: "https://api.github.com/repos/denoland/deno/tarball/refs/tags/v2.1.4",
		commit: {
			sha: "b32ed7516cfdaaff76203ca530796d6a1235568d",
			url: "https://api.github.com/repos/denoland/deno/commits/b32ed7516cfdaaff76203ca530796d6a1235568d",
		},
		node_id: "MDM6UmVmMTMzNDQyMzg0OnJlZnMvdGFncy92Mi4xLjQ=",
	},
	{
		name: "v2.1.3",
		zipball_url: "https://api.github.com/repos/denoland/deno/zipball/refs/tags/v2.1.3",
		tarball_url: "https://api.github.com/repos/denoland/deno/tarball/refs/tags/v2.1.3",
		commit: {
			sha: "7f9b1ff30f7d9880b7c825c2b5f2de3137343d76",
			url: "https://api.github.com/repos/denoland/deno/commits/7f9b1ff30f7d9880b7c825c2b5f2de3137343d76",
		},
		node_id: "MDM6UmVmMTMzNDQyMzg0OnJlZnMvdGFncy92Mi4xLjM=",
	},
	{
		name: "v2.1.2",
		zipball_url: "https://api.github.com/repos/denoland/deno/zipball/refs/tags/v2.1.2",
		tarball_url: "https://api.github.com/repos/denoland/deno/tarball/refs/tags/v2.1.2",
		commit: {
			sha: "2039abe8d2bc82fa800f4118707a48ac6f5e02ae",
			url: "https://api.github.com/repos/denoland/deno/commits/2039abe8d2bc82fa800f4118707a48ac6f5e02ae",
		},
		node_id: "MDM6UmVmMTMzNDQyMzg0OnJlZnMvdGFncy92Mi4xLjI=",
	},
	{
		name: "v2.1.1",
		zipball_url: "https://api.github.com/repos/denoland/deno/zipball/refs/tags/v2.1.1",
		tarball_url: "https://api.github.com/repos/denoland/deno/tarball/refs/tags/v2.1.1",
		commit: {
			sha: "5d71b461530f7c374c08701cef5678a5a4ac5484",
			url: "https://api.github.com/repos/denoland/deno/commits/5d71b461530f7c374c08701cef5678a5a4ac5484",
		},
		node_id: "MDM6UmVmMTMzNDQyMzg0OnJlZnMvdGFncy92Mi4xLjE=",
	},
	{
		name: "v2.1.0",
		zipball_url: "https://api.github.com/repos/denoland/deno/zipball/refs/tags/v2.1.0",
		tarball_url: "https://api.github.com/repos/denoland/deno/tarball/refs/tags/v2.1.0",
		commit: {
			sha: "3da4eca7c1ed97906654671669e0bb3b095bc637",
			url: "https://api.github.com/repos/denoland/deno/commits/3da4eca7c1ed97906654671669e0bb3b095bc637",
		},
		node_id: "MDM6UmVmMTMzNDQyMzg0OnJlZnMvdGFncy92Mi4xLjA=",
	},
	{
		name: "v2.0.6",
		zipball_url: "https://api.github.com/repos/denoland/deno/zipball/refs/tags/v2.0.6",
		tarball_url: "https://api.github.com/repos/denoland/deno/tarball/refs/tags/v2.0.6",
		commit: {
			sha: "8f59d18202e94e5c54ad7e5a79ec1383159e4a20",
			url: "https://api.github.com/repos/denoland/deno/commits/8f59d18202e94e5c54ad7e5a79ec1383159e4a20",
		},
		node_id: "MDM6UmVmMTMzNDQyMzg0OnJlZnMvdGFncy92Mi4wLjY=",
	},
	{
		name: "v2.0.5",
		zipball_url: "https://api.github.com/repos/denoland/deno/zipball/refs/tags/v2.0.5",
		tarball_url: "https://api.github.com/repos/denoland/deno/tarball/refs/tags/v2.0.5",
		commit: {
			sha: "78a799b4947461eb5c6092295cbcdabfe94053f7",
			url: "https://api.github.com/repos/denoland/deno/commits/78a799b4947461eb5c6092295cbcdabfe94053f7",
		},
		node_id: "MDM6UmVmMTMzNDQyMzg0OnJlZnMvdGFncy92Mi4wLjU=",
	},
	{
		name: "v2.0.4",
		zipball_url: "https://api.github.com/repos/denoland/deno/zipball/refs/tags/v2.0.4",
		tarball_url: "https://api.github.com/repos/denoland/deno/tarball/refs/tags/v2.0.4",
		commit: {
			sha: "b7c282d2f80b12b0b2a435780fb0ea2b236ab224",
			url: "https://api.github.com/repos/denoland/deno/commits/b7c282d2f80b12b0b2a435780fb0ea2b236ab224",
		},
		node_id: "MDM6UmVmMTMzNDQyMzg0OnJlZnMvdGFncy92Mi4wLjQ=",
	},
	{
		name: "v2.0.3",
		zipball_url: "https://api.github.com/repos/denoland/deno/zipball/refs/tags/v2.0.3",
		tarball_url: "https://api.github.com/repos/denoland/deno/tarball/refs/tags/v2.0.3",
		commit: {
			sha: "997bd47fc27ad920f3388c94a95829ff45394c84",
			url: "https://api.github.com/repos/denoland/deno/commits/997bd47fc27ad920f3388c94a95829ff45394c84",
		},
		node_id: "MDM6UmVmMTMzNDQyMzg0OnJlZnMvdGFncy92Mi4wLjM=",
	},
	{
		name: "v2.0.2",
		zipball_url: "https://api.github.com/repos/denoland/deno/zipball/refs/tags/v2.0.2",
		tarball_url: "https://api.github.com/repos/denoland/deno/tarball/refs/tags/v2.0.2",
		commit: {
			sha: "22a79ea420e67e783d996d5d1d64983192cb3dd8",
			url: "https://api.github.com/repos/denoland/deno/commits/22a79ea420e67e783d996d5d1d64983192cb3dd8",
		},
		node_id: "MDM6UmVmMTMzNDQyMzg0OnJlZnMvdGFncy92Mi4wLjI=",
	},
	{
		name: "v2.0.1",
		zipball_url: "https://api.github.com/repos/denoland/deno/zipball/refs/tags/v2.0.1",
		tarball_url: "https://api.github.com/repos/denoland/deno/tarball/refs/tags/v2.0.1",
		commit: {
			sha: "99c2aa573057e337f3474d43a7aab8c5e6b4caa2",
			url: "https://api.github.com/repos/denoland/deno/commits/99c2aa573057e337f3474d43a7aab8c5e6b4caa2",
		},
		node_id: "MDM6UmVmMTMzNDQyMzg0OnJlZnMvdGFncy92Mi4wLjE=",
	},
	{
		name: "v2.0.0",
		zipball_url: "https://api.github.com/repos/denoland/deno/zipball/refs/tags/v2.0.0",
		tarball_url: "https://api.github.com/repos/denoland/deno/tarball/refs/tags/v2.0.0",
		commit: {
			sha: "a62c7e036ab6851c0293f407ead635a7331445b7",
			url: "https://api.github.com/repos/denoland/deno/commits/a62c7e036ab6851c0293f407ead635a7331445b7",
		},
		node_id: "MDM6UmVmMTMzNDQyMzg0OnJlZnMvdGFncy92Mi4wLjA=",
	},
	{
		name: "v1.46.3",
		zipball_url: "https://api.github.com/repos/denoland/deno/zipball/refs/tags/v1.46.3",
		tarball_url: "https://api.github.com/repos/denoland/deno/tarball/refs/tags/v1.46.3",
		commit: {
			sha: "a98e146a55b209458160bcd148497310a9e14441",
			url: "https://api.github.com/repos/denoland/deno/commits/a98e146a55b209458160bcd148497310a9e14441",
		},
		node_id: "MDM6UmVmMTMzNDQyMzg0OnJlZnMvdGFncy92MS40Ni4z",
	},
	{
		name: "v1.46.2",
		zipball_url: "https://api.github.com/repos/denoland/deno/zipball/refs/tags/v1.46.2",
		tarball_url: "https://api.github.com/repos/denoland/deno/tarball/refs/tags/v1.46.2",
		commit: {
			sha: "1b62d42631013724432f1ba4a3b04f506450abba",
			url: "https://api.github.com/repos/denoland/deno/commits/1b62d42631013724432f1ba4a3b04f506450abba",
		},
		node_id: "MDM6UmVmMTMzNDQyMzg0OnJlZnMvdGFncy92MS40Ni4y",
	},
	{
		name: "v1.46.1",
		zipball_url: "https://api.github.com/repos/denoland/deno/zipball/refs/tags/v1.46.1",
		tarball_url: "https://api.github.com/repos/denoland/deno/tarball/refs/tags/v1.46.1",
		commit: {
			sha: "de11ff8c556c6922f832f639f54e5f7a6a3096b9",
			url: "https://api.github.com/repos/denoland/deno/commits/de11ff8c556c6922f832f639f54e5f7a6a3096b9",
		},
		node_id: "MDM6UmVmMTMzNDQyMzg0OnJlZnMvdGFncy92MS40Ni4x",
	},
	{
		name: "v1.46.0",
		zipball_url: "https://api.github.com/repos/denoland/deno/zipball/refs/tags/v1.46.0",
		tarball_url: "https://api.github.com/repos/denoland/deno/tarball/refs/tags/v1.46.0",
		commit: {
			sha: "3314a0ceb8f874986d5da9f36f683740bd813750",
			url: "https://api.github.com/repos/denoland/deno/commits/3314a0ceb8f874986d5da9f36f683740bd813750",
		},
		node_id: "MDM6UmVmMTMzNDQyMzg0OnJlZnMvdGFncy92MS40Ni4w",
	},
	{
		name: "v1.45.5",
		zipball_url: "https://api.github.com/repos/denoland/deno/zipball/refs/tags/v1.45.5",
		tarball_url: "https://api.github.com/repos/denoland/deno/tarball/refs/tags/v1.45.5",
		commit: {
			sha: "52fd273834c0675f651577e23785d76f67423ab1",
			url: "https://api.github.com/repos/denoland/deno/commits/52fd273834c0675f651577e23785d76f67423ab1",
		},
		node_id: "MDM6UmVmMTMzNDQyMzg0OnJlZnMvdGFncy92MS40NS41",
	},
	{
		name: "v1.45.4",
		zipball_url: "https://api.github.com/repos/denoland/deno/zipball/refs/tags/v1.45.4",
		tarball_url: "https://api.github.com/repos/denoland/deno/tarball/refs/tags/v1.45.4",
		commit: {
			sha: "c0b1d19d559bfb1fbb65675b3849a9c0396d131f",
			url: "https://api.github.com/repos/denoland/deno/commits/c0b1d19d559bfb1fbb65675b3849a9c0396d131f",
		},
		node_id: "MDM6UmVmMTMzNDQyMzg0OnJlZnMvdGFncy92MS40NS40",
	},
	{
		name: "v1.45.3",
		zipball_url: "https://api.github.com/repos/denoland/deno/zipball/refs/tags/v1.45.3",
		tarball_url: "https://api.github.com/repos/denoland/deno/tarball/refs/tags/v1.45.3",
		commit: {
			sha: "87ce64e57486fc006e82806c9ed8c49f11c2cb73",
			url: "https://api.github.com/repos/denoland/deno/commits/87ce64e57486fc006e82806c9ed8c49f11c2cb73",
		},
		node_id: "MDM6UmVmMTMzNDQyMzg0OnJlZnMvdGFncy92MS40NS4z",
	},
	{
		name: "v1.45.2",
		zipball_url: "https://api.github.com/repos/denoland/deno/zipball/refs/tags/v1.45.2",
		tarball_url: "https://api.github.com/repos/denoland/deno/tarball/refs/tags/v1.45.2",
		commit: {
			sha: "85de4280a1f9fae572a7331db6344cee123ddab7",
			url: "https://api.github.com/repos/denoland/deno/commits/85de4280a1f9fae572a7331db6344cee123ddab7",
		},
		node_id: "MDM6UmVmMTMzNDQyMzg0OnJlZnMvdGFncy92MS40NS4y",
	},
	{
		name: "v1.45.1",
		zipball_url: "https://api.github.com/repos/denoland/deno/zipball/refs/tags/v1.45.1",
		tarball_url: "https://api.github.com/repos/denoland/deno/tarball/refs/tags/v1.45.1",
		commit: {
			sha: "c841d163e3dc344c06f10579672cc5e2b095933f",
			url: "https://api.github.com/repos/denoland/deno/commits/c841d163e3dc344c06f10579672cc5e2b095933f",
		},
		node_id: "MDM6UmVmMTMzNDQyMzg0OnJlZnMvdGFncy92MS40NS4x",
	},
	{
		name: "v1.45.0",
		zipball_url: "https://api.github.com/repos/denoland/deno/zipball/refs/tags/v1.45.0",
		tarball_url: "https://api.github.com/repos/denoland/deno/tarball/refs/tags/v1.45.0",
		commit: {
			sha: "04ff5c731d55f2402e7b08e378eaf6e5a5a4d961",
			url: "https://api.github.com/repos/denoland/deno/commits/04ff5c731d55f2402e7b08e378eaf6e5a5a4d961",
		},
		node_id: "MDM6UmVmMTMzNDQyMzg0OnJlZnMvdGFncy92MS40NS4w",
	},
	{
		name: "v1.44.4",
		zipball_url: "https://api.github.com/repos/denoland/deno/zipball/refs/tags/v1.44.4",
		tarball_url: "https://api.github.com/repos/denoland/deno/tarball/refs/tags/v1.44.4",
		commit: {
			sha: "892e7c20ac6e7bc0601f4c23e64f43187c1b8479",
			url: "https://api.github.com/repos/denoland/deno/commits/892e7c20ac6e7bc0601f4c23e64f43187c1b8479",
		},
		node_id: "MDM6UmVmMTMzNDQyMzg0OnJlZnMvdGFncy92MS40NC40",
	},
	{
		name: "v1.44.3",
		zipball_url: "https://api.github.com/repos/denoland/deno/zipball/refs/tags/v1.44.3",
		tarball_url: "https://api.github.com/repos/denoland/deno/tarball/refs/tags/v1.44.3",
		commit: {
			sha: "ab2ab0f7fc4e7bda16544ef96a5e6ba114e799b5",
			url: "https://api.github.com/repos/denoland/deno/commits/ab2ab0f7fc4e7bda16544ef96a5e6ba114e799b5",
		},
		node_id: "MDM6UmVmMTMzNDQyMzg0OnJlZnMvdGFncy92MS40NC4z",
	},
	{
		name: "v1.44.2",
		zipball_url: "https://api.github.com/repos/denoland/deno/zipball/refs/tags/v1.44.2",
		tarball_url: "https://api.github.com/repos/denoland/deno/tarball/refs/tags/v1.44.2",
		commit: {
			sha: "9ca1320746072001feab9f6a26e9c1518609bd7b",
			url: "https://api.github.com/repos/denoland/deno/commits/9ca1320746072001feab9f6a26e9c1518609bd7b",
		},
		node_id: "MDM6UmVmMTMzNDQyMzg0OnJlZnMvdGFncy92MS40NC4y",
	},
	{
		name: "v1.44.1",
		zipball_url: "https://api.github.com/repos/denoland/deno/zipball/refs/tags/v1.44.1",
		tarball_url: "https://api.github.com/repos/denoland/deno/tarball/refs/tags/v1.44.1",
		commit: {
			sha: "e02a32be2797f7c107d19da8bf2aff5bbcd97bad",
			url: "https://api.github.com/repos/denoland/deno/commits/e02a32be2797f7c107d19da8bf2aff5bbcd97bad",
		},
		node_id: "MDM6UmVmMTMzNDQyMzg0OnJlZnMvdGFncy92MS40NC4x",
	},
	{
		name: "v1.44.0",
		zipball_url: "https://api.github.com/repos/denoland/deno/zipball/refs/tags/v1.44.0",
		tarball_url: "https://api.github.com/repos/denoland/deno/tarball/refs/tags/v1.44.0",
		commit: {
			sha: "f3ffffc682604349b96dbe4ad33daa5dd1a09f63",
			url: "https://api.github.com/repos/denoland/deno/commits/f3ffffc682604349b96dbe4ad33daa5dd1a09f63",
		},
		node_id: "MDM6UmVmMTMzNDQyMzg0OnJlZnMvdGFncy92MS40NC4w",
	},
	{
		name: "v1.43.6",
		zipball_url: "https://api.github.com/repos/denoland/deno/zipball/refs/tags/v1.43.6",
		tarball_url: "https://api.github.com/repos/denoland/deno/tarball/refs/tags/v1.43.6",
		commit: {
			sha: "7df3d5aeec14f24e5fdec1e1e6f5739f1fbeebbe",
			url: "https://api.github.com/repos/denoland/deno/commits/7df3d5aeec14f24e5fdec1e1e6f5739f1fbeebbe",
		},
		node_id: "MDM6UmVmMTMzNDQyMzg0OnJlZnMvdGFncy92MS40My42",
	},
	{
		name: "v1.43.5",
		zipball_url: "https://api.github.com/repos/denoland/deno/zipball/refs/tags/v1.43.5",
		tarball_url: "https://api.github.com/repos/denoland/deno/tarball/refs/tags/v1.43.5",
		commit: {
			sha: "a13c4531fd2c08617767cc8a0788b9e20ac27d45",
			url: "https://api.github.com/repos/denoland/deno/commits/a13c4531fd2c08617767cc8a0788b9e20ac27d45",
		},
		node_id: "MDM6UmVmMTMzNDQyMzg0OnJlZnMvdGFncy92MS40My41",
	},
	{
		name: "v1.43.4",
		zipball_url: "https://api.github.com/repos/denoland/deno/zipball/refs/tags/v1.43.4",
		tarball_url: "https://api.github.com/repos/denoland/deno/tarball/refs/tags/v1.43.4",
		commit: {
			sha: "d64921c1906ee1ac39230c16abe9ff8c546bd645",
			url: "https://api.github.com/repos/denoland/deno/commits/d64921c1906ee1ac39230c16abe9ff8c546bd645",
		},
		node_id: "MDM6UmVmMTMzNDQyMzg0OnJlZnMvdGFncy92MS40My40",
	},
	{
		name: "v1.43.3",
		zipball_url: "https://api.github.com/repos/denoland/deno/zipball/refs/tags/v1.43.3",
		tarball_url: "https://api.github.com/repos/denoland/deno/tarball/refs/tags/v1.43.3",
		commit: {
			sha: "d6ad253882a6c066e0c673ff64e6554a37bb3487",
			url: "https://api.github.com/repos/denoland/deno/commits/d6ad253882a6c066e0c673ff64e6554a37bb3487",
		},
		node_id: "MDM6UmVmMTMzNDQyMzg0OnJlZnMvdGFncy92MS40My4z",
	},
	{
		name: "v1.43.2",
		zipball_url: "https://api.github.com/repos/denoland/deno/zipball/refs/tags/v1.43.2",
		tarball_url: "https://api.github.com/repos/denoland/deno/tarball/refs/tags/v1.43.2",
		commit: {
			sha: "acd75bbd75fdf46c213d7b21093e09349318da5d",
			url: "https://api.github.com/repos/denoland/deno/commits/acd75bbd75fdf46c213d7b21093e09349318da5d",
		},
		node_id: "MDM6UmVmMTMzNDQyMzg0OnJlZnMvdGFncy92MS40My4y",
	},
	{
		name: "v1.43.1",
		zipball_url: "https://api.github.com/repos/denoland/deno/zipball/refs/tags/v1.43.1",
		tarball_url: "https://api.github.com/repos/denoland/deno/tarball/refs/tags/v1.43.1",
		commit: {
			sha: "5ff881a0737eccceed55a0ace3ef3110d5b72b2f",
			url: "https://api.github.com/repos/denoland/deno/commits/5ff881a0737eccceed55a0ace3ef3110d5b72b2f",
		},
		node_id: "MDM6UmVmMTMzNDQyMzg0OnJlZnMvdGFncy92MS40My4x",
	},
	{
		name: "v1.43.0",
		zipball_url: "https://api.github.com/repos/denoland/deno/zipball/refs/tags/v1.43.0",
		tarball_url: "https://api.github.com/repos/denoland/deno/tarball/refs/tags/v1.43.0",
		commit: {
			sha: "5ff881a0737eccceed55a0ace3ef3110d5b72b2f",
			url: "https://api.github.com/repos/denoland/deno/commits/5ff881a0737eccceed55a0ace3ef3110d5b72b2f",
		},
		node_id: "MDM6UmVmMTMzNDQyMzg0OnJlZnMvdGFncy92MS40My4w",
	},
	{
		name: "v1.42.4",
		zipball_url: "https://api.github.com/repos/denoland/deno/zipball/refs/tags/v1.42.4",
		tarball_url: "https://api.github.com/repos/denoland/deno/tarball/refs/tags/v1.42.4",
		commit: {
			sha: "7cb23c5e3ee0b6c416f4c0e34c7c63fdf5024138",
			url: "https://api.github.com/repos/denoland/deno/commits/7cb23c5e3ee0b6c416f4c0e34c7c63fdf5024138",
		},
		node_id: "MDM6UmVmMTMzNDQyMzg0OnJlZnMvdGFncy92MS40Mi40",
	},
	{
		name: "v1.42.3",
		zipball_url: "https://api.github.com/repos/denoland/deno/zipball/refs/tags/v1.42.3",
		tarball_url: "https://api.github.com/repos/denoland/deno/tarball/refs/tags/v1.42.3",
		commit: {
			sha: "a64a257024c9933d90494613ac6b302cc69df6fa",
			url: "https://api.github.com/repos/denoland/deno/commits/a64a257024c9933d90494613ac6b302cc69df6fa",
		},
		node_id: "MDM6UmVmMTMzNDQyMzg0OnJlZnMvdGFncy92MS40Mi4z",
	},
] as const;
