// AUTO-GENERATED by lib/scripts/generate-defaults.mts — do not edit manually
import type { NodeDistVersion, ReleaseScheduleEntry } from "../schemas/node.js";

export const nodeDefaultVersions: ReadonlyArray<NodeDistVersion> = [] as const;

export const nodeDefaultSchedule: Readonly<Record<string, ReleaseScheduleEntry>> = {} as const;
